// apps/preview/next/pages/showcases/Input/InputInvalid.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsInput } from '@barnstormer/react';

export default function InvalidInput() {
  return (
    <>
      <label>
        <span className="text-sm font-medium">Label</span>
        <BsInput invalid />
      </label>
      <div className="flex justify-between">
        <div>
          <p className="text-sm text-negative-700 font-medium mt-0.5">Error</p>
          <p className="typography-hint-xs text-neutral-500 mt-0.5">Help Text</p>
        </div>
      </div>
    </>
  );
}

// #endregion source
InvalidInput.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Input/InputInvalid.vue
<template>
  <label>
    <span class="text-sm font-medium">Label</span>
    <BsInput invalid />
  </label>
  <div class="flex justify-between">
    <div>
      <p class="text-sm text-negative-700 font-medium mt-0.5">Error</p>
      <p class="typography-hint-xs text-neutral-500 mt-0.5">Help Text</p>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { BsInput } from '@barnstormer/vue';
</script>
