// apps/preview/next/pages/showcases/Input/InputReadonly.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsInput } from '@barnstormer/react';

export default function ReadonlyInput() {
  return (
    <>
      <label>
        <span className="text-sm font-medium">Label</span>
        <BsInput value="value" wrapperClassName="!bg-disabled-100 !ring-disabled-300 !ring-1" readOnly />
      </label>
      <div className="flex justify-between">
        <div>
          <p className="typography-hint-xs text-neutral-500 mt-0.5">Help Text</p>
        </div>
      </div>
    </>
  );
}

// #endregion source
ReadonlyInput.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Input/InputReadonly.vue
<template>
  <label>
    <span class="text-sm font-medium">Label</span>
    <BsInput model-value="value" wrapper-class="!bg-disabled-100 !ring-disabled-300 !ring-1" readonly />
  </label>
  <div class="flex justify-between">
    <div>
      <p class="typography-hint-xs text-neutral-500 mt-0.5">Help Text</p>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { BsInput } from '@barnstormer/vue';
</script>
