// packages/barnstormerui/frameworks/react/components/BsDropdown/BsDropdown.tsx
import classNames from 'classnames';
import { useDropdown } from '@barnstormer/react';
import type { BsDropdownProps } from '@barnstormer/react';

export default function BsDropdown(props: BsDropdownProps) {
  const { children, trigger, open: isOpen = false, className, style: containerStyle, ...dropdownOptions } = props;
  const { refs, style: dropdownStyle } = useDropdown({ isOpen, ...dropdownOptions });

  return (
    <div
      ref={refs.setReference}
      className={classNames('w-max', className)}
      style={containerStyle}
      data-testid="dropdown"
    >
      {trigger}
      {isOpen && (
        <div ref={refs.setFloating} style={dropdownStyle} aria-hidden={!isOpen} data-testid="dropdown-content">
          {children}
        </div>
      )}
    </div>
  );
}

// packages/barnstormerui/frameworks/vue/components/BsDropdown/BsDropdown.vue
<script lang="ts" setup>
import { type PropType, toRefs } from 'vue';
import type { Middleware } from '@floating-ui/vue';
import { useDropdown, type BsPopoverPlacement, type BsPopoverStrategy } from '@barnstormer/vue';

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
  placement: {
    type: String as PropType<`${BsPopoverPlacement}` | undefined>,
    default: undefined,
  },
  middleware: {
    type: Array as PropType<Middleware[] | undefined>,
    default: undefined,
  },
  strategy: {
    type: String as PropType<`${BsPopoverStrategy}` | undefined>,
    default: undefined,
  },
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void;
}>();

const { modelValue, placement, middleware, strategy } = toRefs(props);
const {
  referenceRef,
  floatingRef,
  style: dropdownStyle,
} = useDropdown({
  isOpen: modelValue,
  placement,
  middleware,
  strategy,
  onClose: () => emit('update:modelValue', false),
});
</script>
<template>
  <div ref="referenceRef" class="w-max" data-testid="dropdown">
    <slot name="trigger" />
    <div
      v-if="modelValue"
      ref="floatingRef"
      :style="dropdownStyle"
      :aria-hidden="!modelValue || undefined"
      data-testid="dropdown-content"
    >
      <slot />
    </div>
  </div>
</template>
