// apps/preview/nuxt/pages/showcases/RatingButton/Basic.vue
<template>
  <div>
    <p :id="labelId">Select rating</p>
    <BsRatingButton v-model="modelValue" :aria-labelledby="labelId" />
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsRatingButton, useId } from '@barnstormer/vue';
const labelId = useId();
const modelValue = ref();
</script>

// apps/preview/next/pages/showcases/RatingButton/Basic.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { useId, useState } from 'react';
import { BsRatingButton } from '@barnstormer/react';

export default function RatingButtonBasic() {
  const labelId = useId();
  const [rating, setRating] = useState(0);

  return (
    <div>
      <p id={labelId}>Select Rating</p>
      <BsRatingButton value={rating} onChange={setRating} aria-labelledby={labelId} />
    </div>
  );
}

// #endregion source
RatingButtonBasic.getLayout = ShowcasePageLayout;
