// apps/preview/nuxt/pages/showcases/RatingButton/MaxNumber.vue
<template>
  <div>
    <p :id="labelId">Select rating</p>
    <BsRatingButton v-model="modelValue" :max="10" :aria-labelledby="labelId" />
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsRatingButton, useId } from '@barnstormer/vue';
const labelId = useId();
const modelValue = ref(5);
</script>

// apps/preview/next/pages/showcases/RatingButton/MaxNumber.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { useId, useState } from 'react';
import { BsRatingButton } from '@barnstormer/react';

export default function RatingButtonMax() {
  const labelId = useId();
  const [rating, setRating] = useState(5);

  return (
    <div>
      <p id={labelId}>Select Rating</p>
      <BsRatingButton max={10} value={rating} onChange={setRating} aria-labelledby={labelId} />
    </div>
  );
}

// #endregion source
RatingButtonMax.getLayout = ShowcasePageLayout;
