// apps/preview/next/pages/showcases/Badge/BadgePlacement.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsBadge, BsButton, BsIconShoppingCart } from '@barnstormer/react';

export default function BadgePlacement() {
  return (
    <div className="flex gap-3">
      <BsButton className="relative" square variant="tertiary">
        <BsIconShoppingCart />
        <BsBadge content={100} max={99} placement="top-right" />
      </BsButton>

      <BsButton className="relative" square variant="tertiary">
        <BsIconShoppingCart />
        <BsBadge content={100} max={99} placement="bottom-right" />
      </BsButton>

      <BsButton className="relative" square variant="tertiary">
        <BsIconShoppingCart />
        <BsBadge content={100} max={99} placement="top-left" />
      </BsButton>

      <BsButton className="relative" square variant="tertiary">
        <BsIconShoppingCart />
        <BsBadge content={100} max={99} placement="bottom-left" />
      </BsButton>
    </div>
  );
}

// #endregion source
BadgePlacement.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Badge/BadgePlacement.vue
<template>
  <div class="flex gap-3">
    <BsButton class="relative" square variant="tertiary">
      <BsIconShoppingCart />
      <BsBadge :content="content" :max="99" placement="top-right" />
    </BsButton>

    <BsButton class="relative" square variant="tertiary">
      <BsIconShoppingCart />
      <BsBadge :content="content" :max="99" placement="bottom-right" />
    </BsButton>

    <BsButton class="relative" square variant="tertiary">
      <BsIconShoppingCart />
      <BsBadge :content="content" :max="99" placement="top-left" />
    </BsButton>

    <BsButton class="relative" square variant="tertiary">
      <BsIconShoppingCart />
      <BsBadge :content="content" :max="99" placement="bottom-left" />
    </BsButton>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsBadge, BsButton, BsIconShoppingCart } from '@barnstormer/vue';

const content = ref(100);
</script>
