// apps/preview/next/pages/showcases/Badge/BadgeOutline.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsBadge, BsButton, BsIconShoppingCart } from '@barnstormer/react';

export default function BadgeOutline() {
  return (
    <div className="flex gap-3">
      <div className="p-3 bg-white">
        <BsButton className="group relative" square variant="tertiary">
          <BsIconShoppingCart />
          <BsBadge
            content={100}
            max={99}
            className="outline outline-white group-hover:outline-primary-100 group-active:outline-primary-200"
          />
        </BsButton>
      </div>

      <div className="p-3 bg-primary-700">
        <BsButton className="group relative hover:bg-primary-800 active:bg-primary-900" square variant="tertiary">
          <BsIconShoppingCart className="text-white" />
          <BsBadge
            content={100}
            max={99}
            className="outline outline-primary-700 bg-white !text-neutral-900 group-hover:outline-primary-800 group-active:outline-primary-900"
          />
        </BsButton>
      </div>
    </div>
  );
}

// #endregion source
BadgeOutline.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Badge/BadgeOutline.vue
<template>
  <div class="flex gap-3">
    <div class="p-3 bg-white">
      <BsButton class="group relative" square variant="tertiary">
        <BsIconShoppingCart />
        <BsBadge
          :content="content"
          :max="99"
          class="outline outline-white group-hover:outline-primary-100 group-active:outline-primary-200"
        />
      </BsButton>
    </div>

    <div class="p-3 bg-primary-700">
      <BsButton class="group relative hover:bg-primary-800 active:bg-primary-900" square variant="tertiary">
        <BsIconShoppingCart class="text-white" />
        <BsBadge
          :content="content"
          :max="99"
          class="outline outline-primary-700 bg-white !text-neutral-900 group-hover:outline-primary-800 group-active:outline-primary-900"
        />
      </BsButton>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsBadge, BsButton, BsIconShoppingCart } from '@barnstormer/vue';

const content = ref(100);
</script>
