// apps/preview/next/pages/showcases/Scrollable/ScrollByOneItem.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { useState } from 'react';
import classNames from 'classnames';
import { BsScrollable } from '@barnstormer/react';

export default function ScrollableMoveByOne() {
  const itemsLength = 20;
  const [activeIndex, setActiveIndex] = useState(0);

  return (
    <BsScrollable
      wrapperClassName="min-w-0"
      className="items-center w-full"
      activeIndex={activeIndex}
      prevDisabled={activeIndex === 0}
      nextDisabled={activeIndex === itemsLength - 1}
      isActiveIndexCentered
      onPrev={({ preventDefault }) => {
        preventDefault();
        setActiveIndex((currentValue) => currentValue - 1);
      }}
      onNext={({ preventDefault }) => {
        preventDefault();
        setActiveIndex((currentValue) => currentValue + 1);
      }}
    >
      {Array.from({ length: itemsLength }, (_, i) => (
        <div
          key={i}
          className={classNames(
            'flex items-center justify-center text-gray-500 border w-36 h-36 shrink-0 border-negative-300',
            i === activeIndex ? 'border-solid bg-neutral-200' : 'border-dashed bg-neutral-100',
          )}
        >
          {i + 1}
        </div>
      ))}
    </BsScrollable>
  );
}
// #endregion source

ScrollableMoveByOne.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Scrollable/ScrollByOneItem.vue
<template>
  <BsScrollable
    class="items-center w-full"
    :active-index="activeIndex"
    wrapper-class="min-w-0"
    :prev-disabled="activeIndex === 0"
    :next-disabled="activeIndex === itemsLength - 1"
    is-active-index-centered
    @on-prev="
      ({ preventDefault }) => {
        preventDefault();
        activeIndex -= 1;
      }
    "
    @on-next="
      ({ preventDefault }) => {
        preventDefault();
        activeIndex += 1;
      }
    "
  >
    <div
      v-for="(_, index) in Array.from({ length: 20 })"
      :key="index"
      :class="[
        'flex items-center justify-center text-gray-500 border w-36 h-36 shrink-0 border-negative-300',
        index === activeIndex ? 'border-solid bg-neutral-200' : 'border-dashed bg-neutral-100',
      ]"
    >
      {{ index + 1 }}
    </div>
  </BsScrollable>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsScrollable } from '@barnstormer/vue';

const itemsLength = 20;
const activeIndex = ref(0);
</script>
