// apps/preview/nuxt/pages/showcases/Button/ButtonAsLink.vue
<template>
  <div class="flex flex-col items-center space-y-4 xs:block xs:space-x-4">
    <BsButton tag="a" href="#"> Link </BsButton>

    <BsButton :tag="NuxtLink" to="#"> NuxtLink </BsButton>

    <BsButton tag="router-link" to="#"> router-link </BsButton>
  </div>
</template>

<script lang="ts" setup>
import { resolveComponent } from 'vue';
import { BsButton } from '@barnstormer/vue';

const NuxtLink = resolveComponent('NuxtLink');
</script>

// apps/preview/next/pages/showcases/Button/ButtonAsLink.tsx
/* eslint-disable jsx-a11y/anchor-is-valid */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsButton } from '@barnstormer/react';
import Link from 'next/link';

export default function ButtonAsLink() {
  return (
    <div className="flex flex-col items-center space-y-4 xs:block xs:space-x-4">
      <BsButton as="a" href="#">
        Link
      </BsButton>
      <Link href="#" passHref legacyBehavior>
        <BsButton as="a">NextLink</BsButton>
      </Link>
    </div>
  );
}

// #endregion source
ButtonAsLink.getLayout = ShowcasePageLayout;
