// packages/barnstormerui/frameworks/vue/components/BsRatingButton/BsRatingButton.vue
<script lang="ts" setup>
import { type PropType, computed, ref, toRefs } from 'vue';
import {
  BsIconStar,
  BsIconStarFilled,
  BsIconSize,
  BsRatingButtonSize,
  type BsRatingButtonIconSize,
} from '@barnstormer/vue';

const props = defineProps({
  modelValue: {
    type: Number,
    default: 0,
  },
  max: {
    type: Number,
    default: 5,
  },
  disabled: {
    type: Boolean,
    default: false,
  },
  name: {
    type: String,
    default: 'sf-rating-button',
  },
  size: {
    type: String as PropType<`${BsRatingButtonSize}`>,
    default: BsRatingButtonSize.base,
  },
  getLabelText: {
    type: Function as PropType<(value: number) => string>,
    default: (value: number) => `${value} Star${value !== 1 ? 's' : ''}`,
  },
});

const emit = defineEmits<{
  (e: 'update:modelValue', val: number): void;
}>();

const { max, disabled, modelValue } = toRefs(props);
const hoverModel = ref(0);
const icons = computed(() => Array.from({ length: Math.floor(Math.abs(max.value)) }, (_, index) => index + 1));
const isIconFilled = (ratingValue: number) =>
  ratingValue <= hoverModel.value || (hoverModel.value === 0 && ratingValue <= modelValue.value);
const iconSize: Record<BsRatingButtonSize, BsRatingButtonIconSize> = {
  [BsRatingButtonSize.sm]: BsIconSize.base,
  [BsRatingButtonSize.base]: BsIconSize.lg,
  [BsRatingButtonSize.lg]: BsIconSize.xl,
};

const radioModel = computed({
  set(value: number) {
    emit('update:modelValue', value);
  },
  get() {
    return props.modelValue;
  },
});

const handleHoverIn = (ratingValue: number) => {
  if (!disabled.value) {
    hoverModel.value = ratingValue;
  }
};

const handleHoverOut = () => {
  if (!disabled.value) {
    hoverModel.value = 0;
  }
};
</script>

<!-- eslint-disable vuejs-accessibility/no-static-element-interactions -->
<template>
  <div role="radiogroup" class="flex" data-testid="ratingbutton">
    <label
      v-for="ratingValue in icons"
      :key="ratingValue"
      @mouseenter="handleHoverIn(ratingValue)"
      @mouseleave="handleHoverOut"
    >
      <input
        v-model="radioModel"
        type="radio"
        class="sr-only peer"
        :name="name"
        :value="ratingValue"
        :disabled="disabled"
        :aria-label="getLabelText(ratingValue)"
      />
      <slot :is-filled="isIconFilled(ratingValue)" :icon-size="iconSize[size]" :max="max">
        <BsIconStarFilled
          v-if="isIconFilled(ratingValue)"
          role="none"
          class="text-primary-700 cursor-pointer peer-disabled:cursor-default peer-disabled:text-disabled-500 peer-focus-visible:outline"
          :size="iconSize[size]"
        />
        <BsIconStar
          v-else
          role="none"
          class="text-neutral-500 cursor-pointer peer-disabled:cursor-default peer-disabled:text-disabled-500 peer-focus-visible:outline"
          :size="iconSize[size]"
        />
      </slot>
    </label>
  </div>
</template>

// packages/barnstormerui/frameworks/react/components/BsRatingButton/BsRatingButton.tsx
import { useState, type ChangeEvent } from 'react';
import classnames from 'classnames';
import {
  BsIconStar,
  BsIconStarFilled,
  BsIconSize,
  BsRatingButtonSize,
  type BsRatingButtonProps,
  type BsRatingButtonRenderProps,
} from '@barnstormer/react';

function defaultLabelText(value: number) {
  return `${value} Star${value !== 1 ? 's' : ''}`;
}

const renderDefaultIcon = ({ isFilled, iconSize }: BsRatingButtonRenderProps) => {
  if (isFilled) {
    return (
      <BsIconStarFilled
        role="none"
        className="text-primary-700 cursor-pointer peer-disabled:cursor-default peer-disabled:text-disabled-500 peer-focus-visible:outline"
        size={iconSize}
      />
    );
  }
  return (
    <BsIconStar
      role="none"
      className="text-neutral-500 cursor-pointer peer-disabled:cursor-default peer-disabled:text-disabled-500 peer-focus-visible:outline"
      size={iconSize}
    />
  );
};

const iconSize: Record<BsRatingButtonSize, BsRatingButtonRenderProps['iconSize']> = {
  [BsRatingButtonSize.sm]: BsIconSize.base,
  [BsRatingButtonSize.base]: BsIconSize.lg,
  [BsRatingButtonSize.lg]: BsIconSize.xl,
};

export default function BsRatingButton({
  onChange,
  value = 0,
  disabled = false,
  max = 5,
  name = 'sf-rating-button',
  className,
  size = BsRatingButtonSize.base,
  getLabelText = defaultLabelText,
  children = renderDefaultIcon,
  ...attributes
}: BsRatingButtonProps): JSX.Element {
  const [hoverValue, setHoverValue] = useState(0);
  const icons = Array.from({ length: Math.floor(Math.abs(max)) }, (_, index) => index + 1);
  const isIconFilled = (ratingValue: number) => ratingValue <= hoverValue || (hoverValue === 0 && ratingValue <= value);

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    onChange?.(Number(event.target.value));
  };

  const handleHoverIn = (ratingValue: number) => () => {
    if (!disabled) {
      setHoverValue(ratingValue);
    }
  };

  const handleHoverOut = () => {
    if (!disabled) {
      setHoverValue(0);
    }
  };

  return (
    <div role="radiogroup" className={classnames('flex', className)} data-testid="ratingbutton" {...attributes}>
      {icons.map((ratingValue) => (
        <label key={ratingValue} onMouseEnter={handleHoverIn(ratingValue)} onMouseLeave={handleHoverOut}>
          <input
            type="radio"
            name={name}
            value={ratingValue}
            checked={ratingValue === value}
            onChange={handleChange}
            disabled={disabled}
            aria-label={getLabelText(ratingValue)}
            className="sr-only peer"
          />
          {children({ isFilled: isIconFilled(ratingValue), max, iconSize: iconSize[size] })}
        </label>
      ))}
    </div>
  );
}
