// packages/barnstormerui/frameworks/vue/components/BsScrollable/BsScrollable.vue
<script lang="ts">
export default {
  inheritAttrs: false,
};
</script>
<script lang="ts" setup>
import { computed, toRefs, type PropType, type ConcreteComponent, reactive } from 'vue';
import {
  ClassProp,
  BsScrollableDirection,
  BsScrollableButtonsPlacement,
  BsIconChevronLeft,
  BsIconChevronRight,
  BsButton,
  useScrollable,
  type BsScrollableOnDragStartData,
  type BsScrollableOnScrollData,
  type BsScrollableOnPrevData,
  type BsScrollableOnNextData,
  type BsScrollableOnDragEndData,
  type ScrollableOptions,
} from '@barnstormer/vue';

const props = defineProps({
  tag: {
    type: [String, Object] as PropType<string | ConcreteComponent>,
    default: 'div',
  },
  direction: {
    type: String as PropType<`${BsScrollableDirection}`>,
    default: BsScrollableDirection.horizontal,
  },
  buttonsPlacement: {
    type: String as PropType<`${BsScrollableButtonsPlacement}`>,
    default: BsScrollableButtonsPlacement.block,
  },
  wrapperClass: ClassProp,
  activeIndex: {
    type: Number,
    default: undefined,
  },
  reduceMotion: {
    type: Boolean,
    default: undefined,
  },
  drag: {
    type: [Object, Boolean] as PropType<ScrollableOptions['drag']>,
    default: undefined,
  },
  prevDisabled: {
    type: Boolean,
    default: undefined,
  },
  nextDisabled: {
    type: Boolean,
    default: undefined,
  },
  isActiveIndexCentered: {
    type: Boolean,
    default: false,
  },
  buttonPrevAriaLabel: {
    type: String,
    default: 'Previous',
  },
  buttonNextAriaLabel: {
    type: String,
    default: 'Next',
  },
});
const emit = defineEmits<{
  (e: 'onDragStart', data: BsScrollableOnDragStartData): void;
  (e: 'onDragEnd', data: BsScrollableOnDragEndData): void;
  (e: 'onScroll', data: BsScrollableOnScrollData): void;
  (e: 'onPrev', data: BsScrollableOnPrevData): void;
  (e: 'onNext', data: BsScrollableOnNextData): void;
}>();
const { direction, activeIndex, reduceMotion, drag, isActiveIndexCentered } = toRefs(props);

const { containerRef, state, getNextButtonProps, getPrevButtonProps } = useScrollable(
  computed(() => ({
    ...reactive({
      direction,
      activeIndex,
      reduceMotion,
      drag,
      isActiveIndexCentered,
    }),
    onDragStart: (data) => emit('onDragStart', data),
    onDragEnd: (data) => emit('onDragEnd', data),
    onScroll: (data) => emit('onScroll', data),
    onPrev: (data) => emit('onPrev', data),
    onNext: (data) => emit('onNext', data),
  })),
);

const isHorizontal = computed(() => props.direction === BsScrollableDirection.horizontal);
const isFloating = computed(() => props.buttonsPlacement === BsScrollableButtonsPlacement.floating);
const isBlock = computed(() => props.buttonsPlacement === BsScrollableButtonsPlacement.block);
</script>

<template>
  <div :class="['items-center', 'relative', isHorizontal ? 'flex' : 'flex-col h-full inline-flex', wrapperClass]">
    <slot
      v-if="$slots.previousButton && buttonsPlacement !== BsScrollableButtonsPlacement.none"
      v-bind="getPrevButtonProps"
      name="previousButton"
    />
    <BsButton
      v-else-if="buttonsPlacement !== BsScrollableButtonsPlacement.none"
      variant="secondary"
      size="lg"
      square
      :class="[
        '!rounded-full bg-white hidden md:block !ring-neutral-500 !text-neutral-500',
        {
          'mr-4': isBlock && isHorizontal,
          'mb-4 rotate-90': isBlock && !isHorizontal,
          'absolute left-4 z-10': isFloating && isHorizontal,
          'absolute top-4 rotate-90 z-10': isFloating && !isHorizontal,
        },
        isFloating ? 'disabled:hidden' : 'disabled:!ring-disabled-300 disabled:!text-disabled-500',
      ]"
      v-bind="getPrevButtonProps"
      :disabled="prevDisabled || getPrevButtonProps.disabled"
      :aria-label="buttonPrevAriaLabel"
    >
      <BsIconChevronLeft />
    </BsButton>
    <component
      :is="tag"
      ref="containerRef"
      :class="[
        'motion-safe:scroll-smooth',
        {
          'overflow-x-auto flex gap-4': isHorizontal,
          'overflow-y-auto flex flex-col gap-4': !isHorizontal,
          'cursor-grab': state.isDragged,
        },
      ]"
      v-bind="{ ...$attrs, ...props }"
      :disabled="prevDisabled"
    >
      <slot />
    </component>
    <slot
      v-if="$slots.nextButton && buttonsPlacement !== BsScrollableButtonsPlacement.none"
      v-bind="getNextButtonProps"
      name="nextButton"
    />
    <BsButton
      v-else-if="buttonsPlacement !== BsScrollableButtonsPlacement.none"
      variant="secondary"
      size="lg"
      square
      :class="[
        '!rounded-full bg-white hidden md:block !ring-neutral-500 !text-neutral-500',
        {
          'ml-4': isBlock && isHorizontal,
          'mt-4 rotate-90': isBlock && !isHorizontal,
          'absolute right-4 z-10': isFloating && isHorizontal,
          'absolute bottom-4 rotate-90 z-10': isFloating && !isHorizontal,
        },
        isFloating ? 'disabled:hidden' : 'disabled:!ring-disabled-300 disabled:!text-disabled-500',
      ]"
      v-bind="getNextButtonProps"
      :disabled="nextDisabled || getNextButtonProps.disabled"
      :aria-label="buttonNextAriaLabel"
    >
      <BsIconChevronRight />
    </BsButton>
  </div>
</template>

// packages/barnstormerui/frameworks/react/components/BsScrollable/BsScrollable.tsx
/* eslint-disable react/require-default-props */
import { cloneElement, useMemo } from 'react';
import classNames from 'classnames';
import {
  polymorphicForwardRef,
  useScrollable,
  mergeRefs,
  BsButton,
  BsIconChevronLeft,
  BsIconChevronRight,
  BsScrollableDirection,
  BsScrollableButtonsPlacement,
  type BsScrollableProps,
} from '@barnstormer/react';

const defaultScrollableTag = 'div';

const BsScrollable = polymorphicForwardRef<typeof defaultScrollableTag, BsScrollableProps>(
  (
    {
      as,
      direction = BsScrollableDirection.horizontal,
      buttonsPlacement = BsScrollableButtonsPlacement.block,
      activeIndex,
      reduceMotion,
      drag,
      onDragStart,
      onDragEnd,
      onScroll,
      onPrev,
      onNext,
      isActiveIndexCentered,
      className,
      wrapperClassName,
      prevDisabled,
      nextDisabled,
      buttonPrevAriaLabel = 'Previous',
      buttonNextAriaLabel = 'Next',
      style,
      children,
      slotPreviousButton,
      slotNextButton,
      ...attributes
    },
    ref,
  ) => {
    const Tag = as || defaultScrollableTag;
    const isHorizontal = direction === BsScrollableDirection.horizontal;
    const isBlock = buttonsPlacement === BsScrollableButtonsPlacement.block;
    const isFloating = buttonsPlacement === BsScrollableButtonsPlacement.floating;

    const sliderOptions = useMemo(
      () => ({
        direction,
        activeIndex,
        reduceMotion,
        drag,
        onDragStart,
        onDragEnd,
        onScroll,
        onPrev,
        onNext,
        isActiveIndexCentered,
      }),
      [
        direction,
        activeIndex,
        reduceMotion,
        drag,
        isActiveIndexCentered,
        onDragStart,
        onDragEnd,
        onScroll,
        onPrev,
        onNext,
      ],
    );

    const { state, containerRef, getNextButtonProps, getPrevButtonProps } = useScrollable(sliderOptions);

    function PreviousButton({ classNameButton }: { classNameButton?: string }) {
      if (slotPreviousButton) {
        return cloneElement(slotPreviousButton, getPrevButtonProps({ disabled: prevDisabled, onClick: onPrev }));
      }
      return (
        <BsButton
          {...getPrevButtonProps({
            square: true,
            variant: 'secondary',
            size: 'lg',
            disabled: prevDisabled,
            slotPrefix: <BsIconChevronLeft />,
            'aria-label': buttonPrevAriaLabel,
            className: classNames(
              classNameButton,
              isFloating ? 'disabled:hidden' : 'disabled:!ring-disabled-300 disabled:!text-disabled-500',
            ),
          })}
        />
      );
    }

    function NextButton({ classNameButton }: { classNameButton?: string }) {
      if (slotNextButton) {
        return cloneElement(slotNextButton, getNextButtonProps({ disabled: nextDisabled, onClick: onNext }));
      }
      return (
        <BsButton
          {...getNextButtonProps({
            square: true,
            variant: 'secondary',
            size: 'lg',
            disabled: nextDisabled,
            slotPrefix: <BsIconChevronRight />,
            'aria-label': buttonNextAriaLabel,
            className: classNames(
              classNameButton,
              isFloating ? 'disabled:hidden' : 'disabled:!ring-disabled-300 disabled:!text-disabled-500',
            ),
          })}
        />
      );
    }
    return (
      <div
        className={classNames(
          'items-center relative',
          isHorizontal ? 'flex' : 'flex-col h-full inline-flex',
          wrapperClassName,
        )}
      >
        {buttonsPlacement !== BsScrollableButtonsPlacement.none && (
          <PreviousButton
            classNameButton={classNames('!rounded-full bg-white hidden md:block !ring-neutral-500 !text-neutral-500', {
              'mr-4': isBlock && isHorizontal,
              'mb-4 rotate-90': isBlock && !isHorizontal,
              'absolute left-4 z-10': isFloating && isHorizontal,
              'absolute top-4 rotate-90 z-10': isFloating && !isHorizontal,
            })}
          />
        )}
        <Tag
          className={classNames(className, 'motion-safe:scroll-smooth', {
            'overflow-x-auto flex gap-4': isHorizontal,
            'overflow-y-auto flex flex-col gap-4': !isHorizontal,
            'cursor-grab': state.isDragged,
          })}
          ref={mergeRefs([containerRef, ref])}
          {...attributes}
        >
          {children}
        </Tag>
        {buttonsPlacement !== BsScrollableButtonsPlacement.none && (
          <NextButton
            classNameButton={classNames('!rounded-full bg-white hidden md:block !ring-neutral-500 !text-neutral-500', {
              'ml-4': isBlock && isHorizontal,
              'mt-4 rotate-90': isBlock && !isHorizontal,
              'absolute right-4 z-10': isFloating && isHorizontal,
              'absolute bottom-4 rotate-90 z-10': isFloating && !isHorizontal,
            })}
          />
        )}
      </div>
    );
  },
);

export default BsScrollable;
