// apps/preview/next/pages/showcases/Radio/RadioTrailing.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsRadio } from '@barnstormer/react';
import { useState } from 'react';

const radioOptions = [
  {
    label: 'Label',
    value: 'value-1',
    name: 'radio-1',
  },
  {
    label: 'Label 2',
    value: 'value-2',
    name: 'radio-1',
  },
];
export default function RadioWithLabelSmall() {
  const [checkedState, setCheckedState] = useState('');
  return (
    <>
      <div className="-mt-4">
        {radioOptions.map(({ label, value, name }) => (
          <label key={value} className="flex flex-row-reverse items-center justify-between mt-4 cursor-pointer">
            <BsRadio
              name={name}
              value={value}
              checked={checkedState === value}
              onChange={(event) => {
                setCheckedState(event.target.value);
              }}
            />
            <span className="ml-2 text-base font-normal leading-5 font-body">{label}</span>
          </label>
        ))}
      </div>
      <div className="flex justify-between">
        <p className="typography-hint-xs text-neutral-500 mt-0.5">Help text</p>
      </div>
    </>
  );
}

// #endregion source
RadioWithLabelSmall.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Radio/RadioTrailing.vue
<template>
  <div class="-mt-4">
    <label
      v-for="{ name, value, label } in radioOptions"
      :key="value"
      class="flex items-center justify-between mt-4 mr-6 rounded cursor-pointer"
    >
      <span class="text-sm font-normal leading-5 font-body">{{ label }}</span>
      <BsRadio v-model="radioModel" :value="value" :name="name" />
    </label>
  </div>
  <div class="flex justify-between">
    <p class="typography-hint-xs text-neutral-500 mt-0.5">Help text</p>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsRadio } from '@barnstormer/vue';

const radioModel = ref('');
const radioOptions = [
  {
    label: 'Label 1',
    value: 'value-1',
    name: 'radio-1',
  },
  {
    label: 'Label 2',
    value: 'value-2',
    name: 'radio-1',
  },
];
</script>
