// apps/preview/nuxt/pages/showcases/Textarea/TextareaDisabled.vue
<template>
  <label>
    <span class="typography-text-sm font-medium cursor-not-allowed text-disabled-900">Description</span>
    <BsTextarea
      disabled
      placeholder="Write something about yourself..."
      class="w-full !bg-disabled-100 !ring-disabled-300 !ring-1 block"
    />
  </label>
  <p class="typography-hint-xs text-disabled-500 mt-0.5">Do not include personal or financial information.</p>
</template>

<script lang="ts" setup>
import { BsTextarea } from '@barnstormer/vue';
</script>

// apps/preview/next/pages/showcases/Textarea/TextareaDisabled.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsTextarea } from '@barnstormer/react';

export default function DisabledTextareaDemo() {
  return (
    <>
      <label>
        <span className="typography-text-sm font-medium cursor-not-allowed text-disabled-900">Description</span>
        <BsTextarea
          disabled
          placeholder="Write something about yourself..."
          className="w-full !bg-disabled-100 !ring-disabled-300 !ring-1 block"
        />
      </label>
      <p className="typography-hint-xs text-disabled-500  mt-0.5">Do not include personal or financial information.</p>
    </>
  );
}

// #endregion source
DisabledTextareaDemo.getLayout = ShowcasePageLayout;
