// packages/barnstormerui/frameworks/vue/components/BsLink/BsLink.vue
<script lang="ts">
const variantClasses = {
  [BsLinkVariant.primary]:
    'text-primary-700 underline hover:text-primary-800 active:text-primary-900 focus-visible:outline focus-visible:outline-offset focus-visible:rounded-sm',
  [BsLinkVariant.secondary]:
    'underline hover:text-primary-800 active:text-primary-900 focus-visible:outline focus-visible:outline-offset focus-visible:rounded-sm',
};
</script>

<script lang="ts" setup>
import type { PropType, ConcreteComponent } from 'vue';
import { BsLinkVariant } from '@barnstormer/vue';

defineProps({
  tag: {
    type: [String, Object] as PropType<string | ConcreteComponent>,
    default: 'a',
  },
  variant: {
    type: String as PropType<`${BsLinkVariant}`>,
    default: BsLinkVariant.primary,
  },
});
</script>

<template>
  <component
    :is="tag"
    :class="['focus-visible:outline focus-visible:outline-offset focus-visible:rounded-sm', variantClasses[variant]]"
    data-testid="link"
  >
    <slot />
  </component>
</template>

// packages/barnstormerui/frameworks/react/components/BsLink/BsLink.tsx
import classNames from 'classnames';
import { BsLinkVariant, polymorphicForwardRef } from '@barnstormer/react';
import type { BsLinkProps } from '@barnstormer/react';

const defaultLinkTag = 'a';

const BsLink = polymorphicForwardRef<typeof defaultLinkTag, BsLinkProps>((props, ref) => {
  const variantClasses = {
    [BsLinkVariant.primary]: 'text-primary-700 underline hover:text-primary-800 active:text-primary-900',
    [BsLinkVariant.secondary]: 'underline hover:text-primary-800 active:text-primary-900',
  };

  const { as, className, children, variant = BsLinkVariant.primary, ...attributes } = props;
  const Tag = as || defaultLinkTag;

  return (
    <Tag
      ref={ref}
      className={classNames(
        'focus-visible:outline focus-visible:outline-offset focus-visible:rounded-sm',
        variantClasses[variant],
        className,
      )}
      data-testid="link"
      {...attributes}
    >
      {children}
    </Tag>
  );
});

export default BsLink;
