// apps/preview/nuxt/pages/showcases/Chip/Deletable.vue
<template>
  <ul class="flex flex-wrap gap-4 sm:flex-row">
    <li v-for="(item, index) in chipValues" :key="item.value">
      <BsChip
        v-model="selectedValues"
        :input-props="{ value: item.value }"
        @update:model-value="handleChipRemove(index)"
      >
        <template #prefix><BsThumbnail :class="`bg-${item.value}-500`" /></template>
        {{ item.label }}
        <template #suffix>
          <BsIconCloseSm class="text-neutral-500 hover:text-primary-800 active:text-primary-900 disabled:opacity-20" />
        </template>
      </BsChip>
    </li>
  </ul>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsChip, BsIconCloseSm, BsThumbnail } from '@barnstormer/vue';

const chipValues = ref([
  { label: 'Red', value: 'red' },
  { label: 'Blue', value: 'blue' },
  { label: 'Gray', value: 'gray' },
]);
const selectedValues = chipValues.value.map((item) => item.value);
const handleChipRemove = (index: number) => {
  chipValues.value.splice(index, 1);
};
</script>

// apps/preview/next/pages/showcases/Chip/Deletable.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsChip, BsThumbnail, BsIconCloseSm } from '@barnstormer/react';
import { useState } from 'react';

const chipValues = [
  { label: 'Red', value: 'red' },
  { label: 'Blue', value: 'blue' },
  { label: 'Gray', value: 'gray' },
];

export default function DeletableChips() {
  const [chipList, setChipList] = useState(chipValues);
  const handleRemoveChip = (val: string) => {
    const newList = chipList.filter((item) => item.value !== val);

    setChipList(newList);
  };

  return (
    <ul className="flex flex-wrap gap-4 sm:flex-row">
      {chipList.map(({ label, value }) => (
        <li key={value}>
          <BsChip
            className="mr-2"
            inputProps={{ checked: true, onChange: () => handleRemoveChip(value) }}
            slotPrefix={<BsThumbnail className={`bg-${value}-500`} />}
            slotSuffix={
              <BsIconCloseSm className="text-neutral-500 hover:text-primary-800 active:text-primary-900 disabled:opacity-20" />
            }
          >
            {label}
          </BsChip>
        </li>
      ))}
    </ul>
  );
}

// #endregion source

DeletableChips.getLayout = ShowcasePageLayout;
