// apps/preview/nuxt/pages/showcases/Chip/ListOfChips.vue
<template>
  <ul class="flex flex-col flex-wrap gap-4 sm:flex-row">
    <li v-for="({ label, value }, index) in chipValues" :key="index">
      <BsChip :input-props="{ value: value }">
        <template #prefix>
          <BsThumbnail
            :class="{
              'bg-red-500': value === 'red',
              'bg-blue-500': value === 'blue',
              'bg-gray-500': value === 'gray',
            }"
          />
        </template>
        {{ label }}
      </BsChip>
    </li>
  </ul>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsChip, BsThumbnail } from '@barnstormer/vue';

const chipValues = ref([
  { label: 'Red', value: 'red' },
  { label: 'Blue', value: 'blue' },
  { label: 'Gray', value: 'gray' },
]);
</script>

// apps/preview/next/pages/showcases/Chip/ListOfChips.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsChip, BsThumbnail } from '@barnstormer/react';
import classNames from 'classnames';

const chipValues = [
  { label: 'Red', value: 'red' },
  { label: 'Blue', value: 'blue' },
  { label: 'Gray', value: 'gray' },
];

export default function ChipList() {
  return (
    <ul className="flex flex-wrap gap-4 sm:flex-row">
      {chipValues.map(({ label, value }) => (
        <li key={value}>
          <BsChip
            className="mr-2"
            slotPrefix={
              <BsThumbnail
                className={classNames({
                  'bg-red-500': value === 'red',
                  'bg-blue-500': value === 'blue',
                  'bg-gray-500': value === 'gray',
                })}
              />
            }
          >
            {label}
          </BsChip>
        </li>
      ))}
    </ul>
  );
}

// #endregion source
ChipList.getLayout = ShowcasePageLayout;
