// apps/preview/nuxt/pages/showcases/Chip/WithoutLabel.vue
<template>
  <BsChip v-model="chipRedActive" size="sm" square class="mr-2">
    <BsThumbnail class="bg-red-500" size="sm" aria-label="Red thumbnail chip" />
  </BsChip>
  <BsChip v-model="chipBlueActive" square>
    <BsThumbnail class="bg-blue-500" color="blue" size="base" aria-label="Blue thumbnail chip" />
  </BsChip>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsChip, BsThumbnail } from '@barnstormer/vue';

const chipRedActive = ref();
const chipBlueActive = ref();
</script>

// apps/preview/next/pages/showcases/Chip/WithoutLabel.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsChip, BsThumbnail } from '@barnstormer/react';

export default function SquareChips() {
  return (
    <>
      <BsChip size="sm" className="mr-2" square>
        <BsThumbnail className="bg-red-500" size="sm" aria-label="Red thumbnail chip" />
      </BsChip>
      <BsChip square>
        <BsThumbnail className="bg-blue-500" size="base" aria-label="Blue thumbnail chip" />
      </BsChip>
    </>
  );
}

// #endregion source
SquareChips.getLayout = ShowcasePageLayout;
