// apps/preview/nuxt/pages/showcases/Dropdown/BasicDropdown.vue
<template>
  <BsDropdown v-model="isOpen">
    <template #trigger>
      <BsButton @click="toggle()">Toggle</BsButton>
    </template>
    <ul class="p-2 rounded bg-gray-100">
      <li>More</li>
      <li>About</li>
      <li>Settings</li>
    </ul>
  </BsDropdown>
</template>

<script lang="ts" setup>
import { BsDropdown, useDisclosure, BsButton } from '@barnstormer/vue';

const { isOpen, toggle } = useDisclosure();
</script>

// apps/preview/next/pages/showcases/Dropdown/BasicDropdown.tsx
import { ShowcasePageLayout } from '../../showcases';

// #region source
import { BsButton, BsDropdown, useDisclosure } from '@barnstormer/react';

export default function BasicDropdown() {
  const { isOpen, toggle, close } = useDisclosure();
  return (
    <BsDropdown trigger={<BsButton onClick={toggle}>Toggle</BsButton>} open={isOpen} onClose={close}>
      <ul className="p-2 rounded bg-gray-100">
        <li>More</li>
        <li>About</li>
        <li>Settings</li>
      </ul>
    </BsDropdown>
  );
}

// #endregion source
BasicDropdown.getLayout = ShowcasePageLayout;
