// apps/preview/nuxt/pages/showcases/Input/InputCharacters.vue
<template>
  <label>
    <span :class="['text-sm font-medium', { 'cursor-not-allowed text-disabled-500': disabled }]">
      {{ label }}
    </span>
    <BsInput
      v-model="inputValue"
      :wrapper-class="{
        'peer !bg-disabled-100 !ring-disabled-300 !ring-1 !text-disabled-500': disabled || readonly,
      }"
    />
  </label>
  <div class="flex justify-between">
    <div>
      <p v-if="invalid && !disabled" class="text-sm text-negative-700 font-medium mt-0.5">{{ errorText }}</p>
      <p v-if="helpText" :class="['typography-hint-xs mt-0.5', disabled ? 'text-disabled-500' : 'text-neutral-500']">
        {{ helpText }}
      </p>
      <p v-if="requiredText && required" class="mt-1 text-sm font-normal text-neutral-500 before:content-['*']">
        {{ requiredText }}
      </p>
    </div>
    <p
      v-if="characterLimit && !readonly"
      :class="[
        'typography-error-xs mt-0.5',
        disabled ? 'text-disabled-500' : isAboveLimit ? 'text-negative-700 font-medium' : 'text-neutral-500',
      ]"
    >
      {{ charsCount }}
    </p>
  </div>
</template>
<script lang="ts" setup>
import { ref, computed } from 'vue';
import { BsInput } from '@barnstormer/vue';

const characterLimit = ref(25);
const inputValue = ref('');
const readonly = ref(false);
const invalid = ref(false);
const disabled = ref(false);
const required = ref(false);
const requiredText = ref('');
const helpText = ref('Help text');
const label = ref('Label');
const errorText = ref('Error');

const isAboveLimit = computed(() => inputValue.value.length > characterLimit.value);
const charsCount = computed(() => characterLimit.value - inputValue.value.length);
</script>

// apps/preview/next/pages/showcases/Input/InputCharacters.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsInput } from '@barnstormer/react';
import classNames from 'classnames';
import { ChangeEvent, useState } from 'react';

export default function InputWithLimit() {
  const characterLimit = 25;
  const label = 'Label';
  const placeholder = 'placeholder';
  const disabled = false;
  const readonly = false;
  const invalid = false;
  const helpText = 'Help text';
  const required = false;
  const requiredText = 'Required';
  const errorText = 'Error';

  const [value, setValue] = useState('');

  function onChange(event: ChangeEvent<HTMLInputElement>) {
    setValue(event?.target.value);
  }
  const isAboveLimit = characterLimit ? value.length > characterLimit : false;
  const charsCount = characterLimit ? characterLimit - value.length : null;

  const getCharacterLimitClass = () => (isAboveLimit ? 'text-negative-700 font-medium' : 'text-neutral-500');

  return (
    <>
      <label>
        <span
          className={classNames('text-sm font-medium', {
            'cursor-not-allowed text-disabled-500': disabled,
          })}
        >
          {label}
        </span>
        <BsInput
          size="base"
          value={value}
          invalid={false}
          placeholder={placeholder}
          disabled={disabled}
          readOnly={readonly}
          onChange={onChange}
          wrapperClassName={classNames({
            'peer !bg-disabled-100 !ring-disabled-300 !ring-1 !text-disabled-500': disabled || readonly,
          })}
        />
      </label>
      <div className="flex justify-between">
        <div>
          {invalid && !disabled && <p className="text-sm text-negative-700 font-medium mt-0.5">{errorText}</p>}
          {helpText && (
            <p className={classNames('typography-hint-xs mt-0.5', disabled ? 'text-disabled-500' : 'text-neutral-500')}>
              {helpText}
            </p>
          )}
          {requiredText && required ? (
            <p className="mt-1 text-sm font-normal text-neutral-500 before:content-['*']">{requiredText}</p>
          ) : null}
        </div>
        {characterLimit && !readonly ? (
          <p
            className={classNames(
              'typography-error-xs mt-0.5',
              disabled ? 'text-disabled-500' : getCharacterLimitClass(),
            )}
          >
            {charsCount}
          </p>
        ) : null}
      </div>
    </>
  );
}

// #endregion source
InputWithLimit.getLayout = ShowcasePageLayout;
