// apps/preview/nuxt/pages/showcases/Input/InputDisabled.vue
<template>
  <label>
    <span class="text-sm font-medium cursor-not-allowed text-disabled-900">Label</span>
    <BsInput disabled wrapper-class="!bg-disabled-100 !ring-disabled-300 !ring-1" />
  </label>
  <div class="flex justify-between">
    <div>
      <p class="typography-hint-xs text-disabled-500 mt-0.5">Help Text</p>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { BsInput } from '@barnstormer/vue';
</script>

// apps/preview/next/pages/showcases/Input/InputDisabled.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsInput } from '@barnstormer/react';

export default function DisabledInputDemo() {
  return (
    <>
      <label>
        <span className="text-sm font-medium cursor-not-allowed text-disabled-900">Label</span>
        <BsInput disabled wrapperClassName="!bg-disabled-100 !ring-disabled-300 !ring-1" />
      </label>
      <div className="flex justify-between">
        <div>
          <p className="typography-hint-xs text-disabled-500 mt-0.5">Help Text</p>
        </div>
      </div>
    </>
  );
}

// #endregion source
DisabledInputDemo.getLayout = ShowcasePageLayout;
