// apps/preview/nuxt/pages/showcases/Input/InputLabel.vue
<template>
  <div class="flex flex-col gap-y-5">
    <label>
      <span class="text-sm font-medium">Label</span>
      <BsInput size="sm" />
    </label>
    <label>
      <span class="text-sm font-medium">Label</span>
      <BsInput />
    </label>
    <label>
      <span class="text-sm font-medium">Label</span>
      <BsInput size="lg" />
    </label>
  </div>
</template>
<script lang="ts" setup>
import { BsInput } from '@barnstormer/vue';
</script>

// apps/preview/next/pages/showcases/Input/InputLabel.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsInput } from '@barnstormer/react';

export default function InputWithLabel() {
  return (
    <div className="flex flex-col gap-y-5">
      <label>
        <span className="text-sm font-medium">Label</span>
        <BsInput size="sm" />
      </label>
      <label>
        <span className="text-sm font-medium">Label</span>
        <BsInput />
      </label>
      <label>
        <span className="text-sm font-medium">Label</span>
        <BsInput size="lg" />
      </label>
    </div>
  );
}

// #endregion source
InputWithLabel.getLayout = ShowcasePageLayout;
