// apps/preview/next/pages/showcases/Switch/SwitchTrailing.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsSwitch } from '@barnstormer/react';
import { useState } from 'react';

export default function SwitchAlignment() {
  const [checkedState, setCheckedState] = useState(false);
  return (
    <>
      <label className="flex items-center justify-between">
        <span className="text-base text-gray-900 cursor-pointer font-body">Label</span>
        <BsSwitch
          checked={checkedState}
          value="value-1"
          onChange={(event) => {
            setCheckedState(event.target.checked);
          }}
        />
      </label>
      <span className="typography-hint-xs mt-0.5 block text-gray-500">Help text</span>
    </>
  );
}

// #endregion source
SwitchAlignment.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Switch/SwitchTrailing.vue
<template>
  <label class="flex items-center justify-between">
    <span class="text-base text-gray-900 cursor-pointer font-body">Label</span>
    <BsSwitch v-model="modelCheck" value="value" />
  </label>
  <span class="typography-hint-xs mt-0.5 block text-gray-500">Help text</span>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsSwitch } from '@barnstormer/vue';

const modelCheck = ref(false);
</script>
