// apps/preview/nuxt/pages/showcases/Radio/RadioWithoutLabel.vue
<template>
  <BsRadio
    v-for="{ name, value } in radioOptions"
    :key="value"
    v-model="radioModel"
    class="block mt-4"
    :value="value"
    :name="name"
  />
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsRadio } from '@barnstormer/vue';

const radioModel = ref('');
const radioOptions = [
  {
    value: 'value-1',
    name: 'radio-1',
  },
  {
    value: 'value-2',
    name: 'radio-2',
  },
];
</script>

// apps/preview/next/pages/showcases/Radio/RadioWithoutLabel.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsRadio } from '@barnstormer/react';
import { useState } from 'react';

const radioOptions = [
  {
    value: 'value-1',
    name: 'radio-1',
  },
  {
    value: 'value-2',
    name: 'radio-2',
  },
];
export default function RadioWithoutLabel() {
  const [checkedState, setCheckedState] = useState('');
  return (
    <>
      {radioOptions.map(({ name, value }) => (
        <BsRadio
          key={value}
          name={name}
          value={value}
          className="block mb-4"
          checked={checkedState === value}
          onChange={(event) => {
            setCheckedState(event.target.value);
          }}
        />
      ))}
    </>
  );
}

// #endregion source
RadioWithoutLabel.getLayout = ShowcasePageLayout;
