// packages/barnstormerui/frameworks/vue/components/BsModal/BsModal.vue
<script setup lang="ts">
import { ref, toRefs, type PropType, type ConcreteComponent } from 'vue';
import { onClickOutside } from '@vueuse/core';
import { useTrapFocus } from '@barnstormer/vue';

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
  tag: {
    type: [String, Object] as PropType<string | ConcreteComponent>,
    default: '',
  },
  disableClickAway: {
    type: Boolean,
    default: false,
  },
  disableEsc: {
    type: Boolean,
    default: false,
  },
});
const { disableClickAway, disableEsc, modelValue } = toRefs(props);
const emit = defineEmits<{
  (event: 'update:modelValue', isOpen: boolean): void;
}>();

const modalRef = ref<HTMLElement>();

onClickOutside(modalRef, () => {
  if (disableClickAway.value) return;
  emit('update:modelValue', false);
});

const onEscKeyDown = () => {
  if (disableEsc.value) return;
  emit('update:modelValue', false);
};

useTrapFocus(modalRef, {
  trapTabs: true,
  activeState: modelValue,
  initialFocus: false,
  initialFocusContainerFallback: true,
});
</script>

<template>
  <component
    :is="tag || 'div'"
    v-if="modelValue"
    ref="modalRef"
    aria-modal="true"
    data-testid="modal"
    tabindex="-1"
    class="fixed inset-0 w-fit h-fit m-auto p-6 pt-10 lg:p-10 border border-neutral-100 bg-white shadow-xl rounded-xl outline-none"
    @keydown.esc="onEscKeyDown"
  >
    <slot />
  </component>
</template>

// packages/barnstormerui/frameworks/react/components/BsModal/BsModal.tsx
import classNames from 'classnames';
import { useRef } from 'react';
import { useClickAway } from 'react-use';
import { type BsModalProps, polymorphicForwardRef, useTrapFocus, mergeRefs } from '@barnstormer/react';

const defaultModalTag = 'div';

const BsModal = polymorphicForwardRef<typeof defaultModalTag, BsModalProps>(
  ({ as, open, disableClickAway, disableEsc, onClose, className, children, ...attributes }, ref) => {
    const Tag = as || defaultModalTag;
    const modalRef = useRef(null);
    useClickAway(modalRef, () => {
      if (disableClickAway) return;
      onClose?.();
    });

    // eslint-disable-next-line consistent-return
    const onKeyDown = (event: KeyboardEvent) => {
      if (!disableEsc && event.key === 'Escape') {
        onClose?.();
      }
      if ('onKeyDown' in attributes && typeof attributes.onKeyDown === 'function') return attributes.onKeyDown?.(event);
    };

    useTrapFocus(modalRef, {
      trapTabs: true,
      activeState: open,
      initialFocus: false,
      initialFocusContainerFallback: true,
    });

    return open ? (
      <Tag
        ref={mergeRefs([modalRef, ref])}
        className={classNames(
          'fixed inset-0 w-fit h-fit m-auto p-6 pt-10 lg:p-10 border border-neutral-100 bg-white shadow-xl rounded-xl outline-none',
          className,
        )}
        tabIndex="-1"
        aria-modal="true"
        data-testid="modal"
        {...attributes}
        onKeyDown={onKeyDown}
      >
        {children}
      </Tag>
    ) : null;
  },
);

export default BsModal;
