// apps/preview/nuxt/pages/showcases/ListItem/ListItemSlots.vue
<template>
  <BsListItem class="max-w-sm">
    <template #prefix><BsIconTune /></template>
    <span class="break-words">
      Label
      <BsCounter class="ml-2">123</BsCounter>
    </span>
    <span class="text-xs break-words text-neutral-500">Secondary text</span>
    <template #suffix><BsIconChevronRight /></template>
  </BsListItem>
</template>

<script lang="ts" setup>
import { BsListItem, BsCounter, BsIconChevronRight, BsIconTune } from '@barnstormer/vue';
</script>

// apps/preview/next/pages/showcases/ListItem/ListItemSlots.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsListItem, BsCounter, BsIconChevronRight, BsIconTune } from '@barnstormer/react';

export default function ListItemSlots() {
  return (
    <BsListItem className="max-w-sm" slotPrefix={<BsIconTune />} slotSuffix={<BsIconChevronRight />}>
      <div className="break-words">
        Label
        <BsCounter className="ml-2">123</BsCounter>
      </div>
      <span className="text-xs break-words text-neutral-500">Secondary text</span>
    </BsListItem>
  );
}

// #endregion source
ListItemSlots.getLayout = ShowcasePageLayout;
