// apps/preview/nuxt/pages/showcases/ListItem/ListItemSizes.vue
<template>
  <div class="flex flex-col max-w-sm gap-4">
    <BsListItem size="sm">
      <span class="break-words">Label</span>
    </BsListItem>
    <BsListItem>
      <span class="break-words">Label</span>
    </BsListItem>
    <BsListItem size="lg">
      <span class="break-words">Label</span>
    </BsListItem>
  </div>
</template>

<script lang="ts" setup>
import { BsListItem } from '@barnstormer/vue';
</script>

// apps/preview/next/pages/showcases/ListItem/ListItemSizes.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region sources
import { BsListItem } from '@barnstormer/react';

export default function ListItemSizes() {
  return (
    <div className="flex flex-col max-w-sm gap-4">
      <BsListItem size="sm">
        <span className="break-words">Label</span>
      </BsListItem>
      <BsListItem>
        <span className="break-words">Label</span>
      </BsListItem>
      <BsListItem size="lg">
        <span className="break-words">Label</span>
      </BsListItem>
    </div>
  );
}

// #endregion source
ListItemSizes.getLayout = ShowcasePageLayout;
