// apps/preview/nuxt/pages/showcases/Thumbnail/Sizes.vue
<template>
  <div class="flex items-center justify-around max-w-sm">
    <BsThumbnail size="sm" class="mr-2 bg-primary-500" />
    <BsThumbnail size="base" class="mr-2 bg-primary-500" />
    <BsThumbnail size="lg" class="mr-2 bg-primary-500" />
    <BsThumbnail size="xl" class="bg-primary-500" />
  </div>
</template>

<script lang="ts" setup>
import { BsThumbnail } from '@barnstormer/vue';
</script>

// apps/preview/next/pages/showcases/Thumbnail/Sizes.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsThumbnail } from '@barnstormer/react';

export default function ThumbnailSizes() {
  return (
    <div className="flex items-center justify-around max-w-sm">
      <BsThumbnail size="sm" className="bg-primary-500 mr-2" />
      <BsThumbnail size="base" className="bg-primary-500 mr-2" />
      <BsThumbnail size="lg" className="bg-primary-500 mr-2" />
      <BsThumbnail size="xl" className="bg-primary-500" />
    </div>
  );
}

// #endregion source
ThumbnailSizes.getLayout = ShowcasePageLayout;
