// packages/barnstormerui/frameworks/react/components/BsTooltip/BsTooltip.tsx
import { useTooltip } from '@barnstormer/react';
import type { BsTooltipProps } from '@barnstormer/react';

export default function BsTooltip(props: BsTooltipProps) {
  const { children, label, className, style, showArrow, ...tooltipOptions } = props;
  const { isOpen, getTriggerProps, getTooltipProps, getArrowProps } = useTooltip(tooltipOptions);

  return (
    <span {...getTriggerProps({ className, style })} data-testid="tooltip">
      {children}
      {label && isOpen && (
        <div
          {...getTooltipProps({
            role: 'tooltip',
            className: 'bg-black px-2 py-1.5 rounded-md text-white text-xs w-max max-w-[360px] drop-shadow',
          })}
        >
          {label}
          {showArrow && <span {...getArrowProps({ className: 'bg-black rotate-45' })} />}
        </div>
      )}
    </span>
  );
}

// packages/barnstormerui/frameworks/vue/components/BsTooltip/BsTooltip.vue
<script lang="ts" setup>
import { type PropType, toRefs } from 'vue';
import type { Middleware } from '@floating-ui/vue';
import { useTooltip, type BsPopoverPlacement, type BsPopoverStrategy } from '@barnstormer/vue';

const props = defineProps({
  placement: {
    type: String as PropType<`${BsPopoverPlacement}` | undefined>,
    default: undefined,
  },
  middleware: {
    type: Array as PropType<Middleware[] | undefined>,
    default: undefined,
  },
  strategy: {
    type: String as PropType<`${BsPopoverStrategy}` | undefined>,
    default: undefined,
  },
  showArrow: {
    type: Boolean,
    default: false,
  },
  label: {
    type: String,
    required: true,
  },
});

const { placement, middleware, strategy } = toRefs(props);
const { isOpen, triggerProps, tooltipProps, arrowProps } = useTooltip({ placement, middleware, strategy });
</script>
<template>
  <span data-testid="tooltip" v-bind="triggerProps">
    <slot />
    <div
      v-if="label && isOpen"
      role="tooltip"
      class="bg-black px-2 py-1.5 rounded-md text-white text-xs w-max max-w-[360px] drop-shadow"
      v-bind="tooltipProps"
    >
      {{ label }}
      <span v-if="showArrow" v-bind="arrowProps" class="bg-black rotate-45" />
    </div>
  </span>
</template>
