// packages/barnstormerui/frameworks/vue/components/BsCounter/BsCounter.vue
<script setup lang="ts">
import type { PropType } from 'vue';
import { computed, toRefs } from 'vue';
import { BsCounterSize } from '@barnstormer/vue';

const props = defineProps({
  size: {
    type: String as PropType<`${BsCounterSize}`>,
    default: BsCounterSize.base,
  },
  pill: {
    type: Boolean,
    default: false,
  },
});
const { size, pill } = toRefs(props);

const sizeClasses = computed(() => {
  switch (size?.value) {
    case BsCounterSize['3xs']:
      return ['text-3xs', { 'px-1': pill.value }];
    case BsCounterSize['2xs']:
      return ['text-2xs', { 'px-1.5': pill.value }];
    case BsCounterSize.xs:
      return ['text-xs', { 'px-2': pill.value }];
    case BsCounterSize.sm:
      return ['text-sm', { 'px-2.5': pill.value }];
    case BsCounterSize.lg:
      return ['text-lg', { 'px-3.5': pill.value }];
    default:
      return ['text-base', { 'px-3': pill.value }];
  }
});
</script>

<template>
  <span
    class="inline-flex items-center before:content-['('] after:content-[')'] text-neutral-500"
    :class="[
      sizeClasses,
      {
        'rounded-full py-0.5 font-medium ring-1 ring-neutral-200 ring-inset before:content-none after:content-none':
          pill,
      },
    ]"
    data-testid="counter"
  >
    <slot />
  </span>
</template>

// packages/barnstormerui/frameworks/react/components/BsCounter/BsCounter.tsx
import classNames from 'classnames';
import type { BsCounterProps } from '@barnstormer/react';
import { BsCounterSize } from '@barnstormer/react';

export default function BsCounter({
  size = BsCounterSize.base,
  pill = false,
  children,
  className,
  ...attributes
}: BsCounterProps): JSX.Element {
  const sizeClasses: Record<BsCounterSize, string> = {
    [BsCounterSize['3xs']]: classNames('text-3xs', { 'px-1': pill }),
    [BsCounterSize['2xs']]: classNames('text-2xs', { 'px-1.5': pill }),
    [BsCounterSize.xs]: classNames('text-xs', { 'px-2': pill }),
    [BsCounterSize.sm]: classNames('text-sm', { 'px-2.5': pill }),
    [BsCounterSize.base]: classNames('text-base', { 'px-3': pill }),
    [BsCounterSize.lg]: classNames('text-lg', { 'px-3.5': pill }),
  };

  const classes = classNames([
    "inline-flex items-center before:content-['('] after:content-[')'] text-neutral-500",
    sizeClasses[size],
    {
      'rounded-full py-0.5 font-medium ring-1 ring-neutral-200 ring-inset before:content-none after:content-none': pill,
    },
    className,
  ]);

  return (
    <span className={classes} data-testid="counter" {...attributes}>
      {children}
    </span>
  );
}
