// packages/barnstormerui/frameworks/react/components/BsDrawer/BsDrawer.tsx
import classNames from 'classnames';
import { useRef } from 'react';
import { useClickAway } from 'react-use';
import { BsDrawerPlacement, polymorphicForwardRef, mergeRefs } from '@barnstormer/react';
import type { BsDrawerProps } from '@barnstormer/react';

const defaultDrawerTag = 'aside';

const placementClasses = (placementValue: BsDrawerProps['placement']) => ({
  'left-0': placementValue !== BsDrawerPlacement.right,
  'right-0': placementValue !== BsDrawerPlacement.left,
  'top-0': placementValue !== BsDrawerPlacement.bottom,
  'bottom-0': placementValue !== BsDrawerPlacement.top,
});

const BsDrawer = polymorphicForwardRef<typeof defaultDrawerTag, BsDrawerProps>(
  (
    {
      as,
      open,
      placement = BsDrawerPlacement.left,
      disableClickAway,
      disableEsc,
      onClose,
      className,
      children,
      ...attributes
    },
    ref,
  ) => {
    const Tag = as || defaultDrawerTag;
    const drawerRef = useRef(null);
    useClickAway(drawerRef, () => {
      if (disableClickAway) return;
      onClose?.();
    });

    const onKeyDown = (event: KeyboardEvent) => {
      if (disableEsc) return;
      if (event.key === 'Escape') {
        onClose?.();
      }
    };

    return open ? (
      <Tag
        ref={mergeRefs([drawerRef, ref])}
        className={classNames('fixed', placementClasses(placement), className)}
        tabIndex="-1"
        data-testid="drawer"
        {...attributes}
        onKeyDown={onKeyDown}
      >
        {children}
      </Tag>
    ) : null;
  },
);

export default BsDrawer;

// packages/barnstormerui/frameworks/vue/components/BsDrawer/BsDrawer.vue
<script lang="ts" setup>
import { type PropType, type ConcreteComponent, ref, toRefs, computed } from 'vue';
import { onClickOutside } from '@vueuse/core';
import { BsDrawerPlacement } from '@barnstormer/vue';

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
  placement: {
    type: String as PropType<`${BsDrawerPlacement}`>,
    default: BsDrawerPlacement.left,
  },
  tag: {
    type: [String, Object] as PropType<string | ConcreteComponent>,
    default: 'aside',
  },
  disableClickAway: {
    type: Boolean,
    default: false,
  },
  disableEsc: {
    type: Boolean,
    default: false,
  },
});

const { disableClickAway, disableEsc, placement } = toRefs(props);
const emit = defineEmits<{
  (event: 'update:modelValue', isOpen: boolean): void;
}>();

const drawerRef = ref();

onClickOutside(drawerRef, () => {
  if (disableClickAway.value) return;
  emit('update:modelValue', false);
});

const onEscKeyDown = () => {
  if (disableEsc.value) return;
  emit('update:modelValue', false);
};

const placementClasses = computed(() => ({
  'left-0': placement.value !== BsDrawerPlacement.right,
  'right-0': placement.value !== BsDrawerPlacement.left,
  'top-0': placement.value !== BsDrawerPlacement.bottom,
  'bottom-0': placement.value !== BsDrawerPlacement.top,
}));
</script>

<template>
  <component
    :is="tag"
    v-if="modelValue"
    ref="drawerRef"
    class="fixed"
    :class="placementClasses"
    data-testid="drawer"
    tabindex="-1"
    @keydown.esc="onEscKeyDown"
  >
    <slot />
  </component>
</template>
