// apps/preview/next/pages/showcases/Review/WithAvatar.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsRating, BsIconCheck } from '@barnstormer/react';

export default function Review() {
  return (
    <article className="w-full p-4 border rounded-md">
      <header className="flex flex-col items-start pb-4 md:flex-row md:justify-between">
        <div className="flex items-start">
          <img src="http://localhost:3100/@assets/review_avatar.png" alt="Review avatar" className="p-0.5" />
          <div className="flex-col pl-2">
            <span className="text-sm text-neutral-900">Karla</span>
            <span className="flex items-center pr-2 text-xs text-neutral-500">
              <BsRating value={5} max={5} size="xs" className="mr-2" />2 days ago
            </span>
          </div>
        </div>
        <p className="flex items-center text-xs truncate text-primary-700">
          <BsIconCheck size="xs" className="mr-1" /> Verified purchase
        </p>
      </header>
      <div className="text-sm text-neutral-900">I love them</div>
    </article>
  );
}

// #endregion source
Review.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Review/WithAvatar.vue
<template>
  <article class="w-full p-4 border rounded-md">
    <header class="flex flex-col items-start pb-4 md:flex-row md:justify-between">
      <div class="flex items-start">
        <img src="http://localhost:3100/@assets/review_avatar.png" alt="Review avatar" class="p-0.5" />
        <div class="flex-col pl-2">
          <span class="text-sm text-neutral-900">Karla</span>
          <span class="flex items-center pr-2 text-xs text-neutral-500">
            <BsRating :value="5" :max="5" size="xs" class="mr-2" />
            2 days ago
          </span>
        </div>
      </div>
      <p class="flex items-center text-xs truncate text-primary-700">
        <BsIconCheck size="xs" class="mr-1" /> Verified purchase
      </p>
    </header>
    <div class="text-sm text-neutral-900">I love them</div>
  </article>
</template>

<script lang="ts" setup>
import { BsRating, BsIconCheck } from '@barnstormer/vue';
</script>
