// apps/preview/next/pages/examples/BsButton.tsx
import { BsButton, BsButtonProps, BsButtonSize, BsButtonVariant, BsIconSearch, BsIconLock } from '@barnstormer/react';
import { createControlsOptions } from '@barnstormer/preview-shared/utils/controlsOptions';
import { ExamplePageLayout } from '../examples';
import { prepareControls } from '../../components/utils/Controls';
import ComponentExample from '../../components/utils/ComponentExample';

const prefixSlotOptions = createControlsOptions({
  none: undefined,
  'Search icon': <BsIconSearch />,
});
const suffixSlotOptions = createControlsOptions({
  none: undefined,
  'Lock icon': <BsIconLock />,
});

interface ButtonControls extends Omit<BsButtonProps, 'slotPrefix' | 'slotSuffix'> {
  slotPrefix: typeof prefixSlotOptions.defaultOption;
  slotSuffix: typeof suffixSlotOptions.defaultOption;
}

function Example() {
  const { state, controls } = prepareControls<ButtonControls>(
    [
      {
        type: 'text',
        modelName: 'children',
        description: 'Only for demonstration purposes. Default slot',
      },
      {
        type: 'select',
        modelName: 'slotPrefix',
        description: 'slotPrefix',
        propType: 'ReactNode',
        options: prefixSlotOptions.controlsOptions,
      },
      {
        type: 'select',
        modelName: 'slotSuffix',
        description: 'slotSuffix',
        propType: 'ReactNode',
        options: suffixSlotOptions.controlsOptions,
      },
      {
        type: 'text',
        modelName: 'as',
        description: 'Change button tag to a tag or any other tag',
      },
      {
        type: 'select',
        modelName: 'variant',
        options: Object.keys(BsButtonVariant),
      },
      {
        type: 'select',
        modelName: 'size',
        options: Object.keys(BsButtonSize),
      },
      {
        type: 'boolean',
        modelName: 'disabled',
        description: 'Disabled state',
      },
      {
        type: 'boolean',
        modelName: 'square',
        description: 'Remove border radius',
      },
    ],
    {
      children: 'Hello',
      slotPrefix: prefixSlotOptions.defaultOption,
      slotSuffix: suffixSlotOptions.defaultOption,
      disabled: undefined,
      variant: BsButtonVariant.primary,
      size: BsButtonSize.base,
      square: undefined,
    },
  );

  return (
    <ComponentExample controls={{ state, controls }} componentContainerClassName="space-x-2">
      <BsButton
        {...state.get}
        slotPrefix={prefixSlotOptions.getValue(state.get.slotPrefix)}
        slotSuffix={suffixSlotOptions.getValue(state.get.slotSuffix)}
        className="max-w-[200px]"
      >
        {state.get.children}
      </BsButton>
    </ComponentExample>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;

// apps/preview/nuxt/pages/examples/BsButton.vue
<template>
  <ComponentExample :controls-attrs="controlsAttrs">
    <BsButton v-bind="state">
      <template v-if="prefixSlotOptions.getValue(state.prefix)" #prefix>
        <component :is="prefixSlotOptions.getValue(state.prefix)" />
      </template>
      <template v-if="state.SlotDefault" #default>
        {{ state.SlotDefault }}
      </template>
      <template v-if="suffixSlotOptions.getValue(state.suffix)" #suffix>
        <component :is="suffixSlotOptions.getValue(state.suffix)" />
      </template>
    </BsButton>
  </ComponentExample>
</template>

<script lang="ts" setup>
import { ref, h } from 'vue';
import { BsButton, BsButtonVariant, BsButtonSize, BsIconLock, BsIconSearch } from '@barnstormer/vue';
import { createControlsOptions } from '@barnstormer/preview-shared/utils/controlsOptions';
import { prepareControls } from '../../components/utils/Controls.vue';
import ComponentExample from '../../components/utils/ComponentExample.vue';

const prefixSlotOptions = createControlsOptions({
  none: undefined,
  'Search icon': h(BsIconSearch),
});
const suffixSlotOptions = createControlsOptions({
  none: undefined,
  'Lock icon': h(BsIconLock),
});

const { state, controlsAttrs } = prepareControls(
  [
    {
      type: 'text',
      modelName: 'SlotDefault',
      description: 'Only for demonstration purposes. Default slot',
    },
    {
      type: 'text',
      modelName: 'tag',
      description: 'Change <button> tag to any other tag',
    },
    {
      type: 'select',
      modelName: 'prefix',
      description: 'slotPrefix',
      options: prefixSlotOptions.controlsOptions,
    },
    {
      type: 'select',
      modelName: 'suffix',
      description: 'slotSuffix',
      options: suffixSlotOptions.controlsOptions,
    },
    {
      type: 'select',
      modelName: 'variant',
      options: Object.keys(BsButtonVariant),
    },
    {
      type: 'select',
      modelName: 'size',
      options: Object.keys(BsButtonSize),
    },
    {
      type: 'boolean',
      modelName: 'disabled',
    },
    {
      type: 'boolean',
      modelName: 'square',
      description: 'Add even paddings for icon-only usage',
    },
  ],
  {
    SlotDefault: ref('Hello'),
    prefix: ref(prefixSlotOptions.defaultOption),
    suffix: ref(suffixSlotOptions.defaultOption),
    disabled: ref(),
    variant: ref<BsButtonVariant>(BsButtonVariant.primary),
    size: ref<BsButtonSize>(BsButtonSize.base),
    tag: ref(),
    square: ref(),
  },
);
</script>
