// apps/preview/next/pages/examples/BsRadio.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { BsRadio } from '@barnstormer/react';
import classNames from 'classnames';
import { prepareControls } from '../../components/utils/Controls';
import ComponentExample from '../../components/utils/ComponentExample';
import { ExamplePageLayout } from '../examples';

function Example() {
  const { state, controls } = prepareControls(
    [
      {
        type: 'text',
        modelName: 'checked',
        propType: 'string',
        propDefaultValue: '',
      },
      {
        type: 'json',
        propType: 'array',
        modelName: 'radioOptions',
      },
      {
        type: 'boolean',
        modelName: 'disabled',
        propType: 'boolean',
      },
      {
        type: 'boolean',
        modelName: 'invalid',
        propType: 'boolean',
      },
    ],
    {
      id: 'radio-1',
      name: 'radio',
      value: 'radio 1',
      disabled: false,
      invalid: false,
      checked: '',
      radioOptions: [
        {
          label: 'Label',
          value: 'value-1',
          name: 'radio',
        },
        {
          label: 'Label 2',
          value: 'value-2',
          name: 'radio',
        },
      ],
    },
  );
  function onChangeHandler(value: string) {
    state.set({
      checked: value,
    });
  }
  return (
    <ComponentExample controls={{ state, controls }}>
      {state.get.radioOptions.map(({ label, value, name }) => (
        <label
          key={value}
          className={classNames('flex items-center mb-4 cursor-pointer', {
            'text-disabled-900 cursor-not-allowed': state.get.disabled,
          })}
        >
          <BsRadio
            name={name}
            value={value}
            checked={state.get.checked === value}
            disabled={state.get.disabled}
            invalid={state.get.invalid}
            onChange={(event) => {
              onChangeHandler(event.target.value);
            }}
          />
          <span className="ml-2 text-base font-normal leading-6 font-body">{label}</span>
        </label>
      ))}
    </ComponentExample>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;

// apps/preview/nuxt/pages/examples/BsRadio.vue
<template>
  <ComponentExample :controls-attrs="controlsAttrs">
    <label
      v-for="{ name, value, label } in radioOptions"
      :key="value"
      :class="[
        'flex items-center mb-4 cursor-pointer',
        {
          'text-disabled-900 cursor-not-allowed': disabled,
        },
      ]"
    >
      <BsRadio v-model="modelValue" :disabled="disabled" :invalid="invalid" :value="value" :name="name" />
      <span class="ml-2 text-base font-normal leading-6 font-body">{{ label }}</span>
    </label>
  </ComponentExample>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { BsRadio } from '@barnstormer/vue';
import { prepareControls } from '../../components/utils/Controls.vue';
import ComponentExample from '../../components/utils/ComponentExample.vue';

export default defineComponent({
  name: 'BsRadioExample',
  components: {
    BsRadio,
    ComponentExample,
  },
  setup() {
    return {
      ...prepareControls(
        [
          {
            type: 'text',
            modelName: 'modelValue',
            propType: 'string',
            propDefaultValue: '',
            description: 'Selected value',
          },
          {
            type: 'json',
            propType: 'array',
            modelName: 'radioOptions',
          },
          {
            type: 'boolean',
            modelName: 'disabled',
            propType: 'boolean',
          },
          {
            type: 'boolean',
            modelName: 'invalid',
            propType: 'boolean',
          },
        ],
        {
          id: ref('radio-1'),
          name: ref('radio'),
          value: ref('radio-1'),
          disabled: ref(),
          invalid: ref(),
          modelValue: ref(''),
          radioOptions: ref([
            {
              label: 'Label',
              value: 'value-1',
              name: 'radio',
            },
            {
              label: 'Label 2',
              value: 'value-2',
              name: 'radio',
            },
          ]),
        },
      ),
    };
  },
});
</script>
