// apps/preview/next/pages/examples/BsSwitch.tsx
import { BsSwitch, BsSwitchProps } from '@barnstormer/react';
import { prepareControls } from '../../components/utils/Controls';
import ComponentExample from '../../components/utils/ComponentExample';
import { ExamplePageLayout } from '../examples';

function Example() {
  const { state, controls } = prepareControls<Omit<BsSwitchProps, 'onChange'> & { checked: boolean }>(
    [
      {
        type: 'boolean',
        modelName: 'checked',
        propType: 'boolean',
        description: 'Example of getting values from group of Switches',
      },
      {
        type: 'text',
        modelName: 'value',
        propDefaultValue: '',
        propType: 'string',
      },
      {
        type: 'boolean',
        modelName: 'disabled',
        propType: 'boolean',
      },
    ],
    {
      value: 'value',
      disabled: false,
      checked: false,
    },
  );

  function onChange(event: React.ChangeEvent<HTMLInputElement>) {
    const { checked } = event.target;
    state.set({
      checked,
    });
  }

  return (
    <ComponentExample controls={{ state, controls }}>
      <BsSwitch {...state.get} onChange={onChange} />
    </ComponentExample>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;

// apps/preview/nuxt/pages/examples/BsSwitch.vue
<template>
  <ComponentExample :controls-attrs="controlsAttrs">
    <BsSwitch v-model="modelValue" :value="value" :disabled="disabled" />
  </ComponentExample>
</template>

<script lang="ts">
import { ref } from 'vue';
import { BsSwitch } from '@barnstormer/vue';
import { prepareControls } from '../../components/utils/Controls.vue';
import ComponentExample from '../../components/utils/ComponentExample.vue';

export default {
  name: 'BsSwitchExample',
  components: {
    BsSwitch,
    ComponentExample,
  },
  setup() {
    return {
      ...prepareControls(
        [
          {
            type: 'boolean',
            modelName: 'modelValue',
            propDefaultValue: 'false',
            propType: 'boolean',
          },
          {
            type: 'text',
            modelName: 'value',
            propDefaultValue: '',
            propType: 'string',
          },
          {
            type: 'boolean',
            modelName: 'disabled',
            propType: 'boolean',
          },
        ],
        {
          value: ref('value'),
          disabled: ref(false),
          modelValue: ref(),
        },
      ),
    };
  },
};
</script>
