// apps/preview/nuxt/pages/showcases/Filters/Price.vue
<template>
  <BsAccordionItem v-model="open" class="w-full md:max-w-[376px]">
    <template #summary>
      <div class="flex justify-between p-2 mb-2">
        <p class="font-medium">Price</p>
        <BsIconChevronLeft :class="['text-neutral-500', open ? 'rotate-90' : '-rotate-90']" />
      </div>
    </template>
    <fieldset id="radio-price">
      <BsListItem
        v-for="{ id, value, label, counter } in details"
        :key="id"
        tag="label"
        size="sm"
        class="px-1.5 bg-transparent hover:bg-transparent"
      >
        <template #prefix>
          <BsRadio
            v-model="priceModel"
            class="flex items-center"
            name="radio-price"
            :value="value"
            @click="priceModel = priceModel === value ? '' : value"
          />
        </template>
        <p>
          <span :class="['text-sm mr-2', { 'font-medium': priceModel === value }]">{{ label }}</span>
          <BsCounter size="sm">{{ counter }}</BsCounter>
        </p>
      </BsListItem>
    </fieldset>
  </BsAccordionItem>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsAccordionItem, BsCounter, BsIconChevronLeft, BsListItem, BsRadio } from '@barnstormer/vue';

const open = ref(true);
const priceModel = ref('');
const details = [
  { id: 'pr1', label: 'Under $24.99', value: 'under', counter: 123 },
  { id: 'pr2', label: '$25.00 - $49.99', value: '25-49', counter: 100 },
  { id: 'pr3', label: '$50.00 - $99.99', value: '50-99', counter: 12 },
  { id: 'pr4', label: '$100.00 - $199.99', value: '100-199', counter: 3 },
  { id: 'pr5', label: '$200.00 and above', value: 'above', counter: 18 },
];
</script>

// apps/preview/next/pages/showcases/Filters/Price.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsAccordionItem, BsCounter, BsIconChevronLeft, BsListItem, BsRadio } from '@barnstormer/react';
import { useState } from 'react';
import classNames from 'classnames';

const details = [
  { id: 'pr1', label: 'Under $24.99', value: 'under', counter: 123 },
  { id: 'pr2', label: '$25.00 - $49.99', value: '25-49', counter: 100 },
  { id: 'pr3', label: '$50.00 - $99.99', value: '50-99', counter: 12 },
  { id: 'pr4', label: '$100.00 - $199.99', value: '100-199', counter: 3 },
  { id: 'pr5', label: '$200.00 and above', value: 'above', counter: 18 },
];

export default function PriceFilter() {
  const [opened, setOpened] = useState(true);
  const [price, setPrice] = useState<string | null>(null);
  return (
    <BsAccordionItem
      open={opened}
      onToggle={() => setOpened(!opened)}
      className="w-full md:max-w-[376px]"
      summary={
        <div className="flex justify-between p-2 mb-2">
          <p className="mb-2 font-medium typography-headline-5">Price</p>
          <BsIconChevronLeft className={classNames('text-neutral-500', `${opened ? 'rotate-90' : '-rotate-90'}`)} />
        </div>
      }
    >
      <fieldset name="radio-price">
        {details.map(({ label, value, counter }) => (
          <BsListItem
            key={value}
            as="label"
            size="sm"
            disabled={counter === 0}
            className={classNames('px-1.5 bg-transparent hover:bg-transparent', {
              'font-medium': value === price,
            })}
            slotPrefix={
              <BsRadio
                disabled={counter === 0}
                className="flex items-center"
                value={value}
                checked={price === value}
                name="radio-price"
                onChange={() => setPrice(price === value ? null : value)}
              />
            }
          >
            <p>
              <span className="mr-2 text-sm">{label}</span>
              <BsCounter size="sm">{counter}</BsCounter>
            </p>
          </BsListItem>
        ))}
      </fieldset>
    </BsAccordionItem>
  );
}

// #endregion source
PriceFilter.getLayout = ShowcasePageLayout;
