// packages/barnstormerui/frameworks/vue/components/BsAccordionItem/BsAccordionItem.vue
<script lang="ts" setup>
import { ClassProp } from '@barnstormer/vue';

defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
  summaryClass: ClassProp,
});

defineEmits<{
  (event: 'update:modelValue', open: boolean): void;
}>();
</script>

<!-- eslint-disable vuejs-accessibility/no-static-element-interactions -->
<!-- eslint-disable vuejs-accessibility/click-events-have-key-events -->
<template>
  <details :open="modelValue" data-testid="accordion-item">
    <summary
      :class="[
        summaryClass,
        'list-none [&::-webkit-details-marker]:hidden cursor-pointer focus-visible:outline focus-visible:outline-offset focus-visible:rounded-sm',
      ]"
      @click.prevent="$emit('update:modelValue', !modelValue)"
    >
      <slot name="summary" />
    </summary>
    <slot />
  </details>
</template>

// packages/barnstormerui/frameworks/react/components/BsAccordionItem/BsAccordionItem.tsx
import { forwardRef } from 'react';
import type { MouseEvent } from 'react';
import classNames from 'classnames';
import type { BsAccordionItemProps } from '@barnstormer/react';

const BsAccordionItem = forwardRef<HTMLDetailsElement, BsAccordionItemProps>((props, ref) => {
  const { open, onToggle, children, summary, summaryClassName, ...attributes } = props;

  const handleClick = (event: MouseEvent<HTMLElement>) => {
    event.preventDefault();
    onToggle?.(!open);
  };

  return (
    <details ref={ref} open={open} data-testid="accordion-item" {...attributes}>
      <summary
        onClick={handleClick}
        className={classNames(
          summaryClassName,
          'list-none [&::-webkit-details-marker]:hidden cursor-pointer focus-visible:outline focus-visible:outline-offset focus-visible:outline focus-visible:rounded-sm',
        )}
      >
        {summary}
      </summary>
      {children}
    </details>
  );
});

export default BsAccordionItem;
