// packages/barnstormerui/frameworks/vue/components/BsRating/BsRating.vue
<script lang="ts">
const sizeClasses = {
  [BsRatingSize.xs]: 'text-xs',
  [BsRatingSize.sm]: 'text-sm',
  [BsRatingSize.base]: 'text-base',
  [BsRatingSize.lg]: 'text-lg',
  [BsRatingSize.xl]: 'text-xl',
};
</script>

<script lang="ts" setup>
import { computed, toRefs, type PropType } from 'vue';
import { clamp, roundToNearest } from '@barnstormer/shared';
import { BsRatingSize, BsIconStarFilled, BsIconStar, BsIconStarHalf } from '@barnstormer/vue';

const props = defineProps({
  size: {
    type: String as PropType<`${BsRatingSize}`>,
    default: BsRatingSize.base,
  },
  max: {
    type: Number,
    default: 5,
  },
  value: {
    type: Number,
    default: 0,
  },
  halfIncrement: {
    type: Boolean,
    default: false,
  },
  ariaLabel: {
    type: String,
    default: undefined,
  },
});
const { value, max, halfIncrement, ariaLabel } = toRefs(props);

const precision = computed(() => (halfIncrement.value ? 0.5 : 1));
const ratingValue = computed(() => clamp(roundToNearest(value.value, precision.value), 0, max.value));
const partiallyFilled = computed(() => Number(!Number.isInteger(ratingValue.value)));
const filled = computed(() => Math.ceil(ratingValue.value - partiallyFilled.value));
const empty = computed(() => max.value - filled.value - partiallyFilled.value);
const label = computed(() => ariaLabel?.value ?? `${value.value} out of ${max.value}`);
</script>

<template>
  <span
    role="img"
    :ariaLabel="label"
    :title="label"
    :class="['inline-flex items-center text-warning-500', sizeClasses[size]]"
    data-testid="rating"
  >
    <BsIconStarFilled v-for="index in filled" :key="index" aria-hidden="true" class="w-[1.5em] h-[1.5em]" />
    <BsIconStarHalf v-if="partiallyFilled" aria-hidden="true" class="w-[1.5em] h-[1.5em]" />
    <BsIconStar v-for="index in empty" :key="index" aria-hidden="true" class="text-disabled-500 w-[1.5em] h-[1.5em]" />
  </span>
</template>

// packages/barnstormerui/frameworks/react/components/BsRating/BsRating.tsx
import classNames from 'classnames';
import { clamp, roundToNearest } from '@barnstormer/shared';
import { BsIconStarFilled, BsIconStar, BsIconStarHalf, BsRatingSize } from '@barnstormer/react';
import type { BsRatingProps } from '@barnstormer/react';

const sizeClasses = {
  [BsRatingSize.xs]: 'text-xs',
  [BsRatingSize.sm]: 'text-sm',
  [BsRatingSize.base]: 'text-base',
  [BsRatingSize.lg]: 'text-lg',
  [BsRatingSize.xl]: 'text-xl',
};

export default function BsRating({
  size = BsRatingSize.base,
  max = 5,
  value = 0,
  halfIncrement,
  ariaLabel,
  className,
  ...attributes
}: BsRatingProps) {
  const precision = halfIncrement ? 0.5 : 1;
  const ratingValue = clamp(roundToNearest(value, precision), 0, max);
  const partiallyFilled = Number(!Number.isInteger(ratingValue)); // 0 or 1
  const filled = Math.ceil(ratingValue - partiallyFilled);
  const empty = max - filled - partiallyFilled;
  const label = ariaLabel ?? `${value} out of ${max}`;

  return (
    <div
      role="img"
      aria-label={label}
      title={label}
      className={classNames('inline-flex items-center text-warning-500', sizeClasses[size], className)}
      data-testid="rating"
      {...attributes}
    >
      {[...Array(filled).keys()].map((key) => (
        <BsIconStarFilled aria-hidden="true" className="w-[1.5em] h-[1.5em]" key={key} />
      ))}
      {Boolean(partiallyFilled) && <BsIconStarHalf aria-hidden="true" className="w-[1.5em] h-[1.5em]" />}
      {[...Array(empty).keys()].map((key) => (
        <BsIconStar aria-hidden="true" className="text-disabled-500 w-[1.5em] h-[1.5em]" key={key} />
      ))}
    </div>
  );
}
