// apps/preview/next/pages/showcases/LoaderCircular/LoaderCircularSizes.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsLoaderCircular } from '@barnstormer/react';

export default function LoaderCircularSizes() {
  return (
    <div className="flex flex-col gap-4 flex-wrap sm:flex-row mb-6 mr-6">
      <BsLoaderCircular size="xs" />
      <BsLoaderCircular size="sm" />
      <BsLoaderCircular size="base" />
      <BsLoaderCircular />
      <BsLoaderCircular size="lg" />
      <BsLoaderCircular size="xl" />
      <BsLoaderCircular size="2xl" />
      <BsLoaderCircular size="3xl" />
      <BsLoaderCircular size="4xl" />
    </div>
  );
}

// #endregion source
LoaderCircularSizes.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/LoaderCircular/LoaderCircularSizes.vue
<template>
  <div class="flex flex-col gap-4 flex-wrap sm:flex-row mr-6 mb-6">
    <BsLoaderCircular size="xs" />
    <BsLoaderCircular size="sm" />
    <BsLoaderCircular size="base" />
    <BsLoaderCircular />
    <BsLoaderCircular size="lg" />
    <BsLoaderCircular size="xl" />
    <BsLoaderCircular size="2xl" />
    <BsLoaderCircular size="3xl" />
    <BsLoaderCircular size="4xl" />
  </div>
</template>

<script lang="ts" setup>
import { BsLoaderCircular } from '@barnstormer/vue';
</script>
