// apps/preview/nuxt/pages/showcases.vue
<template>
  <div class="e-page-examples">
    <ClientOnly>
      <div v-if="isNotIframe" class="sidebar" :class="!isOpen && 'sidebar-collapsed'">
        <header class="sidebar-heading">
          <h2>Barnstormer UI</h2>
          <h3>Vue Blocks</h3>
        </header>
        <BsButton
          class="sidebar-toggle"
          :variant="BsButtonVariant.tertiary"
          :size="BsButtonSize.sm"
          :aria-label="isOpen ? 'Hide sidebar' : 'Open sidebar'"
          square
          @click="isOpen = !isOpen"
        >
          <template #prefix>
            <BsIconChevronLeft v-if="isOpen" />
            <BsIconChevronRight v-else />
          </template>
        </BsButton>
        <label class="sidebar-search">
          <BsInput v-model="searchModelValue" placeholder="Search" />
          <button type="button" class="sidebar-search__button" @click="searchModelValue = ''">
            <BsIconCloseSm v-if="searchModelValue" class="sidebar-search__button-icon" />
          </button>
        </label>
        <ul class="sidebar-list">
          <template v-for="(groupValue, groupKey) in groups" :key="groupKey">
            <li v-if="groupValue.visible" class="flex flex-col select-none">
              <button
                type="button"
                class="text-left bg-gray-200 px-2 py-1 justify-between cursor-pointer"
                @click="groupValue.open = !groupValue.open"
              >
                {{ groupKey }}<BsIconExpandMore :class="{ 'rotate-180': groupValue.open }" />
              </button>
              <ul v-if="groupValue.open">
                <li v-for="showcaseName in groupValue.showcases" :key="groupKey + showcaseName">
                  <NuxtLink
                    :key="showcaseName"
                    v-slot="{ navigate }"
                    :to="groupItemHref(groupKey, showcaseName)"
                    custom
                  >
                    <BsListItem
                      tag="span"
                      :selected="currentRoute.path === groupItemHref(groupKey, showcaseName)"
                      :class="{ 'font-medium': currentRoute.path === groupItemHref(groupKey, showcaseName) }"
                      @click="navigate"
                    >
                      {{ showcaseName }}
                    </BsListItem>
                  </NuxtLink>
                </li>
              </ul>
            </li>
          </template>
        </ul>
      </div>
    </ClientOnly>
    <div class="e-page">
      <div
        class="e-page-component"
        :class="[
          arePaddingsDisabled && 'e-page-component--no-paddings',
          areScaleDisabled && 'e-page-component--no-scale',
        ]"
      >
        <NuxtPage />
      </div>
    </div>
  </div>
</template>

<script setup>
import {
  BsButton,
  BsButtonVariant,
  BsButtonSize,
  BsListItem,
  BsIconChevronLeft,
  BsIconChevronRight,
  BsIconExpandMore,
  BsInput,
  BsIconCloseSm,
} from '@barnstormer/vue';
import { ref, watch, reactive, onBeforeMount } from 'vue';
import { useControlsSearchParams } from '~/composables/utils/useControlsSearchParams';

const { currentRoute } = useRouter();

const REST_GROUP_NAME = 'Rest';
const files = import.meta.glob('./showcases/**');
const paths = Object.keys(files);
const groupItemHref = (groupName, showcaseName) => {
  return `/showcases/${groupName !== REST_GROUP_NAME ? `${groupName}/` : ''}${showcaseName}`;
};
const groups = reactive(
  paths.reduce((prev, curr) => {
    if (!curr.includes('.vue')) return prev;
    const showcasePathArray = curr.replace('./showcases/', '').split('/');
    const showcaseName = showcasePathArray[showcasePathArray.length - 1].replace('.vue', '');
    const groupName = showcasePathArray.length === 2 ? showcasePathArray[0] : REST_GROUP_NAME;

    const isInUrl = currentRoute.value.href === groupItemHref(groupName, showcaseName);
    if (groupName in prev) {
      prev[groupName].showcases.push(showcaseName);
      if (!prev[groupName].open) prev[groupName].open = isInUrl;
    } else {
      prev[groupName] = {
        showcases: [showcaseName],
        open: ref(isInUrl),
        visible: ref(true),
      };
    }

    return prev;
  }, {}),
);
const isOpen = ref(true);
const isNotIframe = ref(false);
const arePaddingsDisabled = ref(false);
const areScaleDisabled = ref(false);
const searchModelValue = ref('');

const findGroup = (groups, currentRouteHref) =>
  Object.entries(groups).find((group) => {
    return group[1].showcases.find((showcaseName) => {
      return groupItemHref(group[0], showcaseName) === currentRouteHref;
    });
  });

watch(
  [currentRoute, groups],
  ([currentRoute, groups]) => {
    if (!currentRoute || !groups) return;
    const currentGroup = findGroup(groups, currentRoute.path);
    if (!currentGroup) return;
    groups[currentGroup[0]].open = true;
  },
  { immediate: true },
);

watch(
  searchModelValue,
  (searchModelValue) => {
    for (let group in groups) {
      if (searchModelValue) {
        const searchMatch = group.toLowerCase().startsWith(searchModelValue.toLowerCase());
        groups[group].visible = searchMatch;
        groups[group].open = searchMatch;
      } else {
        groups[group].visible = true;
        groups[group].open = false;
      }
    }
  },
  { immediate: true },
);
useControlsSearchParams(reactive({ s: searchModelValue }));

onBeforeMount(() => {
  if (window.self === window.top) {
    isNotIframe.value = true;
  } else {
    window.parent.postMessage('loaded', '*');
    window.addEventListener(
      'message',
      (e) => {
        if (e.data === 'no-paddings') arePaddingsDisabled.value = true;
        else if (e.data === 'no-scale') areScaleDisabled.value = true;
      },
      false,
    );
  }
});
</script>

// apps/preview/next/layouts/Showcases.tsx
import Link from 'next/link';
import { useRouter } from 'next/router';
import { Fragment, type ReactElement, useEffect, useState } from 'react';
import useSWR from 'swr';
import {
  BsButton,
  BsButtonVariant,
  BsButtonSize,
  BsListItem,
  BsIconChevronLeft,
  BsIconChevronRight,
  BsIconExpandMore,
  BsInput,
  BsIconCloseSm,
} from '@barnstormer/react';
import classNames from 'classnames';
import { useControlsSearchParams } from '../composables/utils/useControlsSearchParams';

type GroupsInterface = {
  [key: string]: {
    showcases: string[];
    open: boolean;
    visible: boolean;
  };
};

const fetcher = (url: string) => fetch(url).then((res) => res.json());
export default function ShowcaseLayout({ children }: { children: ReactElement }) {
  const [isOpen, setIsOpen] = useState(true);
  const [isNotIframe, setIsNotIframe] = useState(false);
  const [noPaddings, setNoPaddings] = useState(false);
  const [noScale, setNoScale] = useState(false);
  const [groups, setGroups] = useState<GroupsInterface>({});
  const [search, setSearch] = useState('');

  const router = useRouter();
  const { data: showcases } = useSWR<string[]>(`${router.basePath}/api/getShowcases`, fetcher);

  const REST_GROUP_NAME = 'Rest';

  const groupItemHref = (groupName: string, showcaseName: string) =>
    `/showcases/${groupName !== REST_GROUP_NAME ? `${groupName}/` : ''}${showcaseName}`;

  useEffect(() => {
    const newGroups = (showcases || []).reduce((prev, curr) => {
      const showcasePathArray = curr.split('/');
      const showcaseName = showcasePathArray[showcasePathArray.length - 1].replace('.tsx', '');
      const groupName = showcasePathArray.length === 2 ? showcasePathArray[0] : REST_GROUP_NAME;

      const isInUrl = router.asPath === groupItemHref(groupName, showcaseName);
      if (groupName in prev) {
        prev[groupName].showcases.push(showcaseName);
        // eslint-disable-next-line no-param-reassign
        if (!prev[groupName].open) prev[groupName].open = isInUrl;
      } else {
        // eslint-disable-next-line no-param-reassign
        prev[groupName] = {
          showcases: [showcaseName],
          open: isInUrl,
          visible: true,
        };
      }
      return prev;
    }, {} as GroupsInterface);
    setGroups(newGroups);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [showcases]);

  useEffect(() => {
    setGroups((currentGroups) => {
      const newState = structuredClone(currentGroups);
      // eslint-disable-next-line no-restricted-syntax
      for (const group in groups) {
        if (search) {
          const searchMatch = group.toLowerCase().startsWith(search.toLowerCase());
          newState[group].visible = searchMatch;
          newState[group].open = searchMatch;
        } else {
          newState[group].visible = true;
          newState[group].open = router.asPath.includes(groupItemHref(group, ''));
        }
      }
      return newState;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [search]);

  useControlsSearchParams({
    get: { s: search as any },
    set: (state) => setSearch((state as any).s),
  });

  useEffect(() => {
    if (window.self === window.top) {
      setIsNotIframe(true);
    } else {
      window.parent.postMessage('loaded', '*');

      window.addEventListener(
        'message',
        (e) => {
          if (e.data === 'no-paddings') setNoPaddings(true);
          else if (e.data === 'no-scale') setNoScale(true);
        },
        false,
      );
    }
  }, []);

  return (
    <div className="e-page-examples">
      {isNotIframe ? (
        <div className={`sidebar ${isOpen ? '' : 'sidebar-collapsed'}`}>
          <header className="sidebar-heading">
            <h2>Barnstormer UI</h2>
            <h3>React Blocks</h3>
          </header>
          <BsButton
            className="sidebar-toggle"
            variant={BsButtonVariant.tertiary}
            size={BsButtonSize.sm}
            square
            onClick={() => setIsOpen(!isOpen)}
            slotPrefix={isOpen ? <BsIconChevronLeft /> : <BsIconChevronRight />}
            aria-label={isOpen ? 'Hide sidebar' : 'Open sidebar'}
          />
          <label className="sidebar-search">
            <BsInput value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search" />
            <button type="button" className="sidebar-search__button" onClick={() => setSearch('')}>
              {search ? <BsIconCloseSm className="sidebar-search__button-icon" /> : undefined}
            </button>
          </label>
          <ul className="sidebar-list">
            {Object.keys(groups).map((group) => (
              <Fragment key={group}>
                {/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/click-events-have-key-events */}
                {groups[group].visible && (
                  <li className="flex flex-col select-none">
                    <button
                      type="button"
                      className="text-left bg-gray-200 px-2 py-1 justify-between cursor-pointer"
                      onClick={() =>
                        setGroups((currentGroups) => {
                          const newState = { ...currentGroups, [group]: { ...currentGroups[group] } };
                          newState[group].open = !newState[group].open;
                          return newState;
                        })
                      }
                    >
                      {group}
                      <BsIconExpandMore className={`${groups[group].open ? 'rotate-180' : ''}`} />
                    </button>
                    {groups[group].open ? (
                      <ul>
                        {groups[group].showcases.map((showcaseName) => (
                          <li key={showcaseName} data-sidebar-component={showcaseName}>
                            <Link href={groupItemHref(group, showcaseName)} legacyBehavior>
                              <BsListItem
                                selected={router.pathname === groupItemHref(group, showcaseName)}
                                className={classNames({
                                  'font-medium': router.pathname === groupItemHref(group, showcaseName),
                                })}
                                as="a"
                              >
                                {showcaseName}
                              </BsListItem>
                            </Link>
                          </li>
                        ))}
                      </ul>
                    ) : undefined}
                  </li>
                )}
              </Fragment>
            ))}
          </ul>
        </div>
      ) : null}
      <div className="e-page">
        <div
          className={classNames('e-page-component', {
            'e-page-component--no-paddings': noPaddings,
            'e-page-component--no-scale': noScale,
          })}
        >
          {children}
        </div>
      </div>
    </div>
  );
}
