// apps/preview/next/pages/showcases/Chip/ChipSizes.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsChip } from '@barnstormer/react';

export default function ChipSizes() {
  return (
    <div>
      <BsChip size="sm" className="mr-2">
        Small
      </BsChip>
      <BsChip size="base" className="mr-2">
        Base
      </BsChip>
      <BsChip>Default</BsChip>
    </div>
  );
}

// #endregion source
ChipSizes.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Chip/ChipSizes.vue
<template>
  <BsChip v-model="chipSmallActive" size="sm" class="mr-2"> Small </BsChip>
  <BsChip v-model="chipBaseActive" size="base" class="mr-2"> Base </BsChip>
  <BsChip v-model="chipDefaultActive" size="base"> Default </BsChip>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsChip } from '@barnstormer/vue';

const chipSmallActive = ref();
const chipBaseActive = ref();
const chipDefaultActive = ref();
</script>
