// apps/preview/next/pages/showcases/Chip/ChipWithThumbnail.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsChip, BsThumbnail } from '@barnstormer/react';

export default function ChipWithThumbnail() {
  return (
    <>
      <BsChip size="sm" className="mr-2" slotPrefix={<BsThumbnail className="bg-red-500" size="sm" />}>
        Red
      </BsChip>
      <BsChip slotPrefix={<BsThumbnail className="bg-secondary-400" size="base" />}>Blue</BsChip>
    </>
  );
}

// #endregion source

ChipWithThumbnail.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Chip/ChipWithThumbnail.vue
<template>
  <BsChip v-model="chipRedActive" size="sm" class="mr-2">
    <template #prefix><BsThumbnail class="bg-red-500" size="sm" /></template>
    Red
  </BsChip>
  <BsChip v-model="chipBlueActive">
    <template #prefix><BsThumbnail class="bg-secondary-400" size="base" /></template>
    Blue
  </BsChip>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsChip, BsThumbnail } from '@barnstormer/vue';

const chipRedActive = ref();
const chipBlueActive = ref();
</script>
