// apps/preview/next/pages/showcases/RadioGroup/RadioGroupWithLegend.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
/* eslint-disable jsx-a11y/no-noninteractive-element-to-interactive-role */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsRadio } from '@barnstormer/react';
import { useState } from 'react';

const radioOptions = [
  {
    label: 'Label',
    value: 'value-1',
    name: 'radio-1',
  },
  {
    label: 'Label 2',
    value: 'value-2',
    name: 'radio-1',
  },
];
export default function RadioGroupWithLegend() {
  const [checkedState, setCheckedState] = useState('');
  return (
    <fieldset role="radiogroup">
      <legend className="mb-2 text-sm font-normal text-gray-500">Legend</legend>
      <div className="flex flex-col">
        {radioOptions.map(({ label, value, name }) => (
          <label key={value} className="flex items-center mb-4 cursor-pointer">
            <BsRadio
              name={name}
              value={value}
              checked={checkedState === value}
              onChange={(event) => {
                setCheckedState(event.target.value);
              }}
            />
            <span className="ml-2 text-base font-normal leading-6 font-body">{label}</span>
          </label>
        ))}
      </div>
    </fieldset>
  );
}

// #endregion source
RadioGroupWithLegend.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/RadioGroup/RadioGroupWithLegend.vue
<template>
  <fieldset role="radiogroup">
    <legend class="mb-2 text-sm font-normal text-gray-500">Legend</legend>
    <div class="flex flex-col">
      <label
        v-for="{ label, name, value } in radioOptions"
        :key="`${value}-${name}`"
        class="flex items-center mb-4 mr-6 rounded cursor-pointer"
      >
        <BsRadio v-model="radioGroupModelValue" :value="value" :name="name" />
        <span class="ml-2 text-base font-normal leading-6 font-body">{{ label }}</span>
      </label>
    </div>
  </fieldset>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsRadio } from '@barnstormer/vue';

const radioGroupModelValue = ref('');
const radioOptions = [
  {
    label: 'Label',
    value: 'value-1',
    name: 'radio-1',
  },
  {
    label: 'Label 2',
    value: 'value-2',
    name: 'radio-1',
  },
];
</script>
