// apps/preview/nuxt/pages/showcases/ProgressLinear/ProgressLinearLabel.vue
<template>
  <div class="flex flex-col gap-4">
    <BsProgressLinear size="lg" :value="value" class="w-24" :aria-label="`${value}%`" />
    <label class="inline-flex items-center gap-2">
      <BsProgressLinear class="w-24" size="lg" :value="value" />
      <span class="font-medium text-lg">{{ value }}%</span>
    </label>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsProgressLinear } from '@barnstormer/vue';

const value = ref(70);
</script>

// apps/preview/next/pages/showcases/ProgressLinear/ProgressLinearLabel.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsProgressLinear } from '@barnstormer/react';

export default function ProgressLinearWithLabel() {
  const value = 70;

  return (
    <div className="flex flex-col gap-4">
      <BsProgressLinear size="lg" value={value} className="w-12" aria-label={`${value}%`} />
      <label className="inline-flex items-center gap-2">
        <BsProgressLinear className="w-12" size="lg" value={value} />
        <span className="font-medium text-lg">{value}%</span>
      </label>
    </div>
  );
}

// #endregion source
ProgressLinearWithLabel.getLayout = ShowcasePageLayout;
