// apps/preview/next/pages/showcases/Checkout/CheckoutAddressForm.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsSelect, BsInput, BsCheckbox, BsButton } from '@barnstormer/react';
import { FormEventHandler, ChangeEvent, FocusEvent, useState } from 'react';

// Here you should provide a list of countries you want to support
// or use an up-to-date country list like: https://www.npmjs.com/package/country-list
const countries = ['Germany', 'Great Britain', 'Poland', 'United States of America'] as const;
const states = ['California', 'Florida', 'New York', 'Texas'] as const;

export default function AddressForm() {
  const [streetIsValid, setStreetIsValid] = useState(true);

  const validateStreet = (e: ChangeEvent<HTMLInputElement> | FocusEvent<HTMLInputElement>) => {
    setStreetIsValid(!!e.target.value);
  };

  const onSubmit: FormEventHandler<HTMLFormElement> = (e) => {
    e.preventDefault();
    /* your submit handler e.g.: */
    const form = e.target as HTMLFormElement;

    // data can be accessed in form of FormData
    const formData = new FormData(form);
    // or JSON object
    const formJSON = Object.fromEntries(formData.entries());
    console.log(formJSON);
  };

  return (
    <form className="p-4 flex gap-4 flex-wrap text-neutral-900" onSubmit={onSubmit}>
      <h2 className="w-full typography-headline-4 md:typography-headline-3 font-bold">Billing address</h2>
      <label className="w-full md:w-auto flex-grow flex flex-col gap-0.5 mt-4 md:mt-0">
        <span className="typography-text-sm font-medium">First Name</span>
        <BsInput name="firstName" autoComplete="given-name" required />
      </label>
      <label className="w-full md:w-auto flex-grow flex flex-col gap-0.5">
        <span className="typography-text-sm font-medium">Last Name</span>
        <BsInput name="lastName" autoComplete="family-name" required />
      </label>
      <label className="w-full flex flex-col gap-0.5">
        <span className="typography-text-sm font-medium">Phone</span>
        <BsInput name="phone" type="tel" autoComplete="tel" required />
      </label>
      <label className="w-full flex flex-col gap-0.5 flex flex-col gap-0.5">
        <span className="typography-text-sm font-medium">Country</span>
        <BsSelect name="country" placeholder="-- Select --" autoComplete="country-name" required>
          {countries.map((countryName) => (
            <option key={countryName}>{countryName}</option>
          ))}
        </BsSelect>
      </label>
      <div className="w-full md:w-auto flex-grow flex flex-col gap-0.5">
        <label>
          <span className="typography-text-sm font-medium">Street</span>
          <BsInput
            name="street"
            autoComplete="address-line1"
            className="mt-0.5"
            onBlur={validateStreet}
            onChange={validateStreet}
            required
            invalid={!streetIsValid}
          />
        </label>
        <div className="flex flex-colr mt-0.5">
          {!streetIsValid && (
            <strong className="typography-error-sm text-negative-700 font-medium">Please provide a street name</strong>
          )}
          <small className="typography-hint-xs text-neutral-500 mt-0.5">Street address or P.O. Box</small>
        </div>
      </div>
      <div className="w-full flex flex-col gap-0.5 md:w-[120px]">
        <label>
          <span className="typography-text-sm font-medium">Apt#, Suite, etc</span>
          <BsInput name="aptNo" className="mt-0.5" />
        </label>
        <small className="typography-hint-xs text-neutral-500 mt-0.5">Optional</small>
      </div>
      <label className="w-full flex flex-col gap-0.5">
        <span className="typography-text-sm font-medium">City</span>
        <BsInput name="city" autoComplete="address-level2" required />
      </label>
      <label className="w-full md:w-auto flex flex-col gap-0.5 flex-grow">
        <span className="typography-text-sm font-medium">State</span>
        <BsSelect name="state" placeholder="-- Select --" autoComplete="address-level1" required>
          {states.map((stateName) => (
            <option key={stateName}>{stateName}</option>
          ))}
        </BsSelect>
      </label>
      <label className="w-full flex flex-col gap-0.5 md:w-[120px]">
        <span className="typography-text-sm font-medium">ZIP Code</span>
        <BsInput name="zipCode" placeholder="eg. 12345" autoComplete="postal-code" required />
      </label>

      <label className="w-full flex items-center gap-2">
        <BsCheckbox name="useAsShippingAddress" />
        Use as shipping address
      </label>

      <div className="w-full flex gap-4 mt-4 md:mt-0 md:justify-end">
        <BsButton type="reset" variant="secondary" className="w-full md:w-auto">
          Clear all
        </BsButton>
        <BsButton type="submit" className="w-full md:w-auto">
          Save
        </BsButton>
      </div>
    </form>
  );
}

// #endregion source
AddressForm.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Checkout/CheckoutAddressForm.vue
<template>
  <form class="p-4 flex gap-4 flex-wrap text-neutral-900" @submit.prevent="onSubmit">
    <h2 class="w-full typography-headline-4 md:typography-headline-3 font-bold">Billing address</h2>
    <label class="w-full md:w-auto flex-grow flex flex-col gap-0.5 mt-4 md:mt-0">
      <span class="typography-text-sm font-medium">First Name</span>
      <BsInput name="firstName" autocomplete="given-name" required />
    </label>
    <label class="w-full md:w-auto flex-grow flex flex-col gap-0.5">
      <span class="typography-text-sm font-medium">Last Name</span>
      <BsInput name="lastName" autocomplete="family-name" required />
    </label>
    <label class="w-full flex flex-col gap-0.5">
      <span class="typography-text-sm font-medium">Phone</span>
      <BsInput name="phone" type="tel" autocomplete="tel" required />
    </label>
    <label class="w-full flex flex-col gap-0.5 flex flex-col gap-0.5">
      <span class="typography-text-sm font-medium">Country</span>
      <BsSelect name="country" placeholder="-- Select --" autocomplete="country-name" required>
        <option v-for="countryName in countries" :key="countryName">{{ countryName }}</option>
      </BsSelect>
    </label>
    <div class="w-full md:w-auto flex-grow flex flex-col gap-0.5">
      <label>
        <span class="typography-text-sm font-medium">Street</span>
        <BsInput
          name="street"
          autocomplete="address-line1"
          class="mt-0.5"
          required
          :invalid="!streetIsValid"
          @blur="streetIsValid = !!$event.target.value"
          @update:model-value="streetIsValid = !!$event"
        />
      </label>
      <div class="flex flex-colr mt-0.5">
        <strong v-if="!streetIsValid" class="typography-error-sm text-negative-700 font-medium">
          Please provide a valid street name
        </strong>
        <small class="typography-hint-xs text-neutral-500">Street address or P.O. Box</small>
      </div>
    </div>
    <div class="w-full flex flex-col gap-0.5 md:w-[120px]">
      <label>
        <span class="typography-text-sm font-medium">Apt#, Suite, etc</span>
        <BsInput name="aptNo" class="mt-0.5" />
      </label>
      <small class="typography-hint-xs text-neutral-500 mt-0.5">Optional</small>
    </div>
    <label class="w-full flex flex-col gap-0.5">
      <span class="typography-text-sm font-medium">City</span>
      <BsInput name="city" autocomplete="address-level2" required />
    </label>
    <label class="w-full md:w-auto flex flex-col gap-0.5 flex-grow">
      <span class="typography-text-sm font-medium">State</span>
      <BsSelect name="state" placeholder="-- Select --" autocomplete="address-level1" required>
        <option v-for="stateName in states" :key="stateName">{{ stateName }}</option>
      </BsSelect>
    </label>
    <label class="w-full flex flex-col gap-0.5 md:w-[120px]">
      <span class="typography-text-sm font-medium">ZIP Code</span>
      <BsInput name="zipCode" placeholder="eg. 12345" autocomplete="postal-code" required />
    </label>

    <label class="w-full flex items-center gap-2">
      <BsCheckbox name="useAsShippingAddress" />
      Use as shipping address
    </label>

    <div class="w-full flex gap-4 mt-4 md:mt-0 md:justify-end">
      <BsButton type="reset" variant="secondary" class="w-full md:w-auto">Clear all</BsButton>
      <BsButton type="submit" class="w-full md:w-auto">Save</BsButton>
    </div>
  </form>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsSelect, BsInput, BsCheckbox, BsButton } from '@barnstormer/vue';

// Here you should provide a list of countries you want to support
// or use an up-to-date country list like: https://www.npmjs.com/package/country-list
const countries = ['Germany', 'Great Britain', 'Poland', 'United States of America'] as const;
const states = ['California', 'Florida', 'New York', 'Texas'] as const;

const streetIsValid = ref(true);

const onSubmit = (e: Event) => {
  /* your submit handler, e.g.: */
  const form = e.target as HTMLFormElement;

  // data can be accessed in form of FormData
  const formData = new FormData(form);
  // or JSON object
  const formJSON = Object.fromEntries(formData.entries());
  console.log(formJSON);
};
</script>
