// apps/preview/next/pages/showcases/Checkout/CheckoutDeliveryOptions.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsRadio, BsListItem } from '@barnstormer/react';
import { useState } from 'react';

const deliveryOptions = [
  {
    name: 'Standard',
    cost: 'Free',
    date: 'Thursday, September 15',
  },
  {
    name: 'Express',
    cost: '$5.00',
    date: 'Tomorrow, September 12',
  },
];

export default function DeliveryOptions() {
  const [checkedState, setCheckedState] = useState('');

  return (
    <div>
      {deliveryOptions.map(({ name, cost, date }) => (
        <BsListItem
          as="label"
          key={name}
          slotPrefix={
            <BsRadio
              name="delivery-options"
              value={name}
              checked={checkedState === name}
              onChange={(event) => {
                setCheckedState(event.target.value);
              }}
            />
          }
          slotSuffix={<span className="text-gray-900">{cost}</span>}
          className="!items-start max-w-sm border rounded-md border-neutral-200 first-of-type:mr-4 first-of-type:mb-4"
        >
          {name}
          <span className="text-xs text-gray-500 break-words">{date}</span>
        </BsListItem>
      ))}
    </div>
  );
}

// #endregion source
DeliveryOptions.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Checkout/CheckoutDeliveryOptions.vue
<template>
  <BsListItem
    v-for="({ name, cost, date }, index) in deliveryOptions"
    :key="index"
    tag="label"
    class="!items-start max-w-sm border rounded-md border-neutral-200 first-of-type:mr-4 first-of-type:mb-4"
  >
    {{ name }}
    <span class="text-xs text-gray-500 break-words">{{ date }}</span>
    <template #prefix>
      <BsRadio v-model="radioModel" :value="name" name="delivery-options" />
    </template>
    <template #suffix>
      <span class="text-gray-900">{{ cost }}</span>
    </template>
  </BsListItem>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsRadio, BsListItem } from '@barnstormer/vue';

const deliveryOptions = [
  {
    name: 'Standard',
    cost: 'Free',
    date: 'Thursday, September 15',
  },
  {
    name: 'Express',
    cost: '$5.00',
    date: 'Tomorrow, September 12',
  },
];
const radioModel = ref('');
</script>
