// apps/preview/nuxt/pages/showcases/Rating/SingleStar.vue
<template>
  <div class="flex flex-col gap-2">
    <div class="font-medium typography-text-xs">
      <BsIconStarFilled class="text-warning-500 w-[1.5em] h-[1.5em]" />
      {{ value }}
    </div>
    <div class="font-medium typography-text-sm">
      <BsIconStarFilled class="text-warning-500 w-[1.5em] h-[1.5em]" />
      {{ value }}
    </div>
    <div class="font-medium">
      <BsIconStarFilled class="text-warning-500 w-[1.5em] h-[1.5em]" />
      {{ value }}
    </div>
    <div class="font-medium typography-text-lg">
      <BsIconStarFilled class="text-warning-500 w-[1.5em] h-[1.5em]" />
      {{ value }}
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsIconStarFilled } from '@barnstormer/vue';

const value = ref(4.5);
</script>

// apps/preview/next/pages/showcases/Rating/SingleStar.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsIconStarFilled } from '@barnstormer/react';

export default function SingleStarRating() {
  const value = 4.5;
  return (
    <div className="flex flex-col gap-2">
      <div className="font-medium typography-text-xs">
        <BsIconStarFilled className="text-warning-500 w-[1.5em] h-[1.5em]" />
        {value}
      </div>
      <div className="font-medium typography-text-sm">
        <BsIconStarFilled className="text-warning-500 w-[1.5em] h-[1.5em]" />
        {value}
      </div>
      <div className="font-medium">
        <BsIconStarFilled className="text-warning-500 w-[1.5em] h-[1.5em]" />
        {value}
      </div>
      <div className="font-medium typography-text-lg">
        <BsIconStarFilled className="text-warning-500 w-[1.5em] h-[1.5em]" />
        {value}
      </div>
    </div>
  );
}

// #endregion source
SingleStarRating.getLayout = ShowcasePageLayout;
