// apps/preview/nuxt/components/utils/Controls.vue
<template>
  <client-only>
    <div class="e-page-controls" :class="{ 'e-page-controls--collapsed': !previewBottomOpen }" v-bind="$attrs">
      <div class="heading-wrapper">
        <h1 class="heading">Controls</h1>

        <BsButton
          :variant="BsButtonVariant.tertiary"
          :size="BsButtonSize.sm"
          @click="previewBottomOpen = !previewBottomOpen"
        >
          {{ previewBottomOpen ? 'Close' : 'Open' }}
          <template #suffix>
            <component :is="previewBottomOpen ? 'BsIconExpandMore' : 'BsIconExpandLess'" />
          </template>
        </BsButton>
      </div>
      <div class="table-wrapper">
        <table aria-label="Controls table">
          <thead class="table-heading">
            <tr>
              <th class="whitespace-nowrap">Prop Name</th>
              <th class="whitespace-nowrap">Value</th>
              <th class="whitespace-nowrap">Type</th>
              <th class="whitespace-nowrap">Default Value</th>
              <th class="whitespace-nowrap">Required</th>
              <th class="whitespace-nowrap">Description</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(control, index) in controls" :key="index" class="props">
              <td :class="[control.type === 'text' && 'align-middle']">
                <span :id="control.modelName">{{ control.modelName }}</span>
              </td>
              <td class="value">
                <template v-if="control.type === 'select'">
                  <select v-model="proxyModels[control.modelName]" :aria-labelledby="control.modelName">
                    <option
                      v-for="(options, optionIndex) in control.options || [{}]"
                      :key="`${control.modelName}-${index}-${optionIndex}`"
                      :value="(options as ControlOptionBind).value || (options as ControlOptionBind).label || options"
                    >
                      {{ (options as ControlOptionBind).label || options }}
                    </option>
                  </select>
                </template>
                <template v-else-if="control.type === 'boolean'">
                  <div class="switch-wrapper">
                    <label class="switch">
                      <input
                        v-model="proxyModels[control.modelName]"
                        type="checkbox"
                        :aria-labelledby="control.modelName"
                      />
                      <span class="slider" />
                    </label>
                    <span class="ml-2">{{ proxyModels[control.modelName] }}</span>
                  </div>
                </template>
                <template v-else>
                  <div
                    v-for="(options, optionIndex) in control.options || [{}]"
                    :key="`${control.modelName}-${index}-${optionIndex}`"
                    class="flex items-center"
                  >
                    <label class="flex items-center">
                      <textarea
                        v-if="control.type === 'json'"
                        rows="10"
                        v-bind="(options as ControlOptionBind).bind"
                        :value="JSON.stringify(proxyModels[control.modelName], undefined, 2)"
                        :name="`${control.modelName}-${index}`"
                        :aria-labelledby="control.modelName"
                        @input="proxyModels[control.modelName] = JSON.parse($event.target?.value)"
                      >
                      </textarea>
                      <input
                        v-else-if="control.type === 'range'"
                        v-bind="(options as ControlOptionBind).bind"
                        v-model="proxyModels[control.modelName]"
                        :type="control.type"
                        :name="`${control.modelName}-${index}`"
                        :aria-labelledby="control.modelName"
                      />
                      <input
                        v-else-if="control.type === 'text'"
                        v-bind="(options as ControlOptionBind).bind"
                        v-model="proxyModels[control.modelName]"
                        class="border rounded-md"
                        :type="control.type"
                        :name="`${control.modelName}-${index}`"
                        :aria-labelledby="control.modelName"
                      />
                      <input
                        v-else
                        v-bind="(options as ControlOptionBind).bind"
                        v-model="proxyModels[control.modelName]"
                        :type="control.type"
                        :name="`${control.modelName}-${index}`"
                        :aria-labelledby="control.modelName"
                      />
                      <span v-if="options.hasOwnProperty('label')" class="pl-2">{{
                        (options as ControlOptionBind).label
                      }}</span>
                      <span v-else-if="typeof options === 'string'" class="pl-2">{{ options }}</span>
                    </label>
                  </div>
                </template>
              </td>
              <td class="propType">
                <span>{{ control.propType }}</span>
              </td>
              <td class="propDefaultValue">{{ control.propDefaultValue }}</td>
              <td class="required">{{ control?.isRequired?.toString() }}</td>
              <td class="description">{{ control.description }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </client-only>
</template>

<script lang="ts">
import { toRefs, computed, reactive, Ref, defineComponent, PropType } from 'vue';
import { BsButton, BsButtonVariant, BsButtonSize, BsIconExpandMore, BsIconExpandLess } from '@barnstormer/vue';
import { useControlsSearchParams } from '../../composables/utils/useControlsSearchParams';

type RefValueUnknown = Ref<unknown>;
type ControlOptionBind = {
  bind?: Record<string, unknown>;
  label?: string;
  value?: string | number;
};
export type Controls = {
  type?: 'range' | 'radio' | 'checkbox' | 'text' | 'select' | 'boolean' | 'json';
  modelName: string;
  model?: RefValueUnknown;
  description?: string;
  propDefaultValue?: string | number | boolean;
  propType?: string;
  isRequired?: boolean;
  options?: (ControlOptionBind | string)[] | readonly (ControlOptionBind | string)[];
}[];
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function prepareControls<T extends { [k: string]: any }>(controlsObject: Controls, models: T) {
  const on: Record<string, (e: string | number | boolean | []) => void> = {};
  const controls = controlsObject.map((control) => {
    if (!('isRequired' in control)) control.isRequired = false;
    on[`onUpdate:${control.modelName}`] = (e: string | number | boolean | []) => {
      models[control.modelName].value = e;
    };
    return { ...control, model: models[control.modelName] };
  });

  return {
    controlsAttrs: {
      controls,
      ...on,
    },
    state: reactive(models),
    // this won't work for every prop name because of a nuxt 3 bug
    // see: https://github.com/nuxt/framework/issues/9851
    // FIXME: after nuxt bug is fixed
    ...models,
  };
}

export default defineComponent({
  name: 'Controls',
  components: {
    BsButton,
    BsIconExpandLess,
    BsIconExpandMore,
  },
  inheritAttrs: false,
  props: {
    controls: {
      type: Array as PropType<Controls>,
      default: () => [],
    },
  },
  setup(props, { emit }) {
    const { controls } = toRefs(props);
    const proxyModels = reactive<Record<string, unknown>>({});
    controls.value.forEach((control) => {
      proxyModels[control.modelName] = computed({
        get: () => control?.model?.value,
        set: (value) => emit(`update:${control.modelName}`, value),
      });
    });

    return {
      BsButtonVariant,
      BsButtonSize,
      ...useControlsSearchParams(proxyModels),
      proxyModels: reactive(proxyModels),
    };
  },
});
</script>

// apps/preview/next/components/utils/Controls.tsx
import classNames from 'classnames';
import { ChangeEvent, useState } from 'react';
import { BsButton, BsButtonVariant, BsButtonSize, BsIconExpandLess, BsIconExpandMore } from '@barnstormer/react';
import { useControlsSearchParams } from '../../composables/utils/useControlsSearchParams';
import { ControlOptionBind, ControlsProps, ControlsType } from './types';

export const prepareControls = <T extends {}>(controls: ControlsType, models: T): ControlsProps<T> => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [formData, setFormData] = useState<T>(models);
  controls.forEach((control) => {
    // eslint-disable-next-line no-param-reassign
    if (!('isRequired' in control)) control.isRequired = false;
  });

  const setState: ControlsProps<T>['state']['set'] = (nextState) => {
    if (typeof nextState === 'function') {
      setFormData(nextState);
    }
    setFormData((currentState) => ({ ...currentState, ...nextState }));
  };

  return {
    controls,
    state: {
      set: setState,
      get: formData,
    },
  };
};

export default function Controls<T extends { [k: string]: any }>({ controls, state, className }: ControlsProps<T>) {
  function handleOnChangeValue<E extends HTMLElement>(e: ChangeEvent<E & { value: unknown }>, name: string) {
    state.set({ [name]: e.target.value } as T);
  }

  function handleJsonOnChangeValue<E extends HTMLElement>(e: ChangeEvent<E & { value: string }>, name: string) {
    state.set({ [name]: JSON.parse(e.target.value) } as T);
  }

  function handleCheckbox(e: ChangeEvent<HTMLInputElement>, name: string, currentValue: string | boolean | []) {
    const { value } = e.target;
    if (Array.isArray(currentValue)) {
      const newValue: string[] = [...currentValue];
      const valueItemIndex = newValue.indexOf(value);
      if (valueItemIndex === -1) {
        newValue.push(value);
      } else {
        newValue.splice(valueItemIndex, 1);
      }
      state.set({ [name]: newValue } as T);
    } else {
      state.set({
        [name]: typeof currentValue === 'string' ? currentValue === value : !currentValue,
      } as T);
    }
  }

  const checkboxValue = (option: ControlOptionBind | string) =>
    typeof option === 'string' ? option : option.value || option.label;

  const {
    previewBottomOpen: [previewBottomOpen, setPreviewBottomOpen],
  } = useControlsSearchParams(state);

  return (
    <div className={classNames(className, 'e-page-controls', { 'e-page-controls--collapsed': !previewBottomOpen })}>
      <div className="heading-wrapper">
        <h1 className="heading">Controls</h1>

        <BsButton
          variant={BsButtonVariant.tertiary}
          size={BsButtonSize.sm}
          onClick={() => setPreviewBottomOpen(!previewBottomOpen)}
          slotSuffix={previewBottomOpen ? <BsIconExpandMore /> : <BsIconExpandLess />}
        >
          {previewBottomOpen ? 'Close' : 'Open'}
        </BsButton>
      </div>
      <div className="table-wrapper">
        <table aria-label="Controls table">
          <thead className="table-heading">
            <tr>
              <th className="whitespace-nowrap">Prop Name</th>
              <th className="whitespace-nowrap">Value</th>
              <th className="whitespace-nowrap">Type</th>
              <th className="whitespace-nowrap">Default Value</th>
              <th className="whitespace-nowrap">Required</th>
              <th className="whitespace-nowrap">Description</th>
            </tr>
          </thead>
          <tbody>
            {controls.map((control, index) => (
              // eslint-disable-next-line react/no-array-index-key
              <tr key={index} className="props">
                <td
                  className={`${
                    control.type !== 'checkbox' && control.type !== 'radio' ? 'align-middle' : 'align-top'
                  }`}
                >
                  <span id={control.modelName}>{control.modelName}</span>
                </td>
                <td className="value">
                  {((): JSX.Element | JSX.Element[] => {
                    switch (control.type) {
                      case 'select':
                        return (
                          <select
                            value={state.get[control.modelName]}
                            aria-labelledby={control.modelName}
                            onChange={(e) => handleOnChangeValue<HTMLSelectElement>(e, control.modelName)}
                          >
                            {(control?.options || ([{}] as NonNullable<ControlsType[number]['options']>)).map(
                              (option, optionIndex) => (
                                <option
                                  // eslint-disable-next-line react/no-array-index-key
                                  key={`${control.modelName}-${index}-${optionIndex}`}
                                  value={
                                    (option as ControlOptionBind).value ||
                                    (option as ControlOptionBind).label ||
                                    (option as string)
                                  }
                                >
                                  {(option as ControlOptionBind).label || (option as string)}
                                </option>
                              ),
                            )}
                          </select>
                        );
                      case 'boolean':
                        return (
                          <div className="switch-wrapper">
                            <label className="switch">
                              <input
                                checked={state.get[control.modelName]}
                                value={state.get[control.modelName]}
                                aria-labelledby={control.modelName}
                                onChange={() =>
                                  state.set((currentState) => ({
                                    ...currentState,
                                    [control.modelName]: !currentState[control.modelName],
                                  }))
                                }
                                type="checkbox"
                              />
                              <span className="slider" />
                            </label>
                            <span className="ml-2">{state.get[control.modelName]?.toString()}</span>
                          </div>
                        );
                      default:
                        return (control?.options || ([{}] as NonNullable<ControlsType[number]['options']>)).map(
                          (option, optionIndex) => (
                            // eslint-disable-next-line react/no-array-index-key
                            <div key={`${control.modelName}-${index}-${optionIndex}`} className="flex items-center">
                              <label className="flex items-center">
                                {(() => {
                                  switch (control.type) {
                                    case 'json':
                                      return (
                                        <textarea
                                          rows={10}
                                          {...(option as ControlOptionBind).bind}
                                          className="border rounded-md"
                                          aria-labelledby={control.modelName}
                                          value={JSON.stringify(state.get[control.modelName], undefined, 2) as string}
                                          onChange={(e) => handleJsonOnChangeValue(e, control.modelName)}
                                        />
                                      );
                                    case 'range':
                                    case 'text':
                                      return (
                                        <input
                                          {...(option as ControlOptionBind).bind}
                                          value={state.get[control.modelName] as number | string}
                                          className="border rounded-md"
                                          type={control.type}
                                          aria-labelledby={control.modelName}
                                          onChange={(e) => handleOnChangeValue(e, control.modelName)}
                                        />
                                      );
                                    default:
                                      return (
                                        <input
                                          {...(option as ControlOptionBind).bind}
                                          value={checkboxValue(option)}
                                          type={control.type}
                                          aria-labelledby={control.modelName}
                                          onChange={(e) => {
                                            // eslint-disable-next-line @typescript-eslint/no-unused-expressions
                                            control.type === 'checkbox'
                                              ? handleCheckbox(
                                                  e,
                                                  control.modelName,
                                                  state.get[control.modelName] as string | [],
                                                )
                                              : handleOnChangeValue(e, control.modelName);
                                          }}
                                          name={`${control.modelName}-${index}`}
                                        />
                                      );
                                  }
                                })()}
                                {typeof option === 'string' ? (
                                  <span className="pl-2">{option}</span>
                                ) : (
                                  'label' in option && (
                                    <span className="pl-2">{(option as ControlOptionBind).label}</span>
                                  )
                                )}
                              </label>
                            </div>
                          ),
                        );
                    }
                  })()}
                </td>
                <td className="propType">
                  <span>{control.propType}</span>
                </td>
                <td className="propDefaultValue">{control.propDefaultValue}</td>
                <td className="required">{control?.isRequired?.toString()}</td>
                <td className="description">{control.description}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
