// apps/preview/next/pages/showcases/Textarea/TextareaAutoresize.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */

import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsTextarea } from '@barnstormer/react';
import { attach } from '@frsource/autoresize-textarea';
import { useEffect, useRef } from 'react';

export default function TextareaAutoresize() {
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => {
    if (textareaRef.current) {
      attach(textareaRef.current);
    }
  }, []);
  return (
    <>
      <label>
        <span className="typography-text-sm font-medium">Description</span>
        <BsTextarea ref={textareaRef} className="w-full h-max-[500px] block" size="sm" aria-label="Label size sm" />
      </label>
      <p className="typography-hint-xs text-neutral-500 mt-0.5">Do not include personal or financial information.</p>
    </>
  );
}

// #endregion source
TextareaAutoresize.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Textarea/TextareaAutoresize.vue
<template>
  <label>
    <span class="typography-text-sm font-medium">Description</span>
    <BsTextarea ref="textareaRef" class="w-full h-max-[500px] block" />
  </label>
  <p class="typography-hint-xs text-neutral-500 mt-0.5">Do not include personal or financial information.</p>
</template>

<script setup lang="ts">
import { BsTextarea } from '@barnstormer/vue';
import { attach } from '@frsource/autoresize-textarea';
import { ref, onMounted } from 'vue';
import { unrefElement } from '@vueuse/core';

const textareaRef = ref();
onMounted(() => {
  attach(unrefElement(textareaRef));
});
</script>
