// apps/preview/next/pages/showcases/Button/ButtonContent.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsButton, BsIconHome, BsIconStar, BsIconShoppingCart } from '@barnstormer/react';

export default function ButtonContent() {
  return (
    <div className="flex flex-col items-center space-y-4 xs:flex-row xs:space-y-0 xs:space-x-4">
      <BsButton slotPrefix={<BsIconHome />}>Home</BsButton>

      <BsButton slotSuffix={<BsIconStar />}>Hello</BsButton>

      <BsButton square aria-label="Add to cart">
        <BsIconShoppingCart />
      </BsButton>
    </div>
  );
}
// #endregion source
ButtonContent.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Button/ButtonContent.vue
<template>
  <div class="flex flex-col items-center space-y-4 xs:flex-row xs:space-y-0 xs:space-x-4">
    <BsButton>
      <template #prefix>
        <BsIconHome />
      </template>
      Home
    </BsButton>

    <BsButton>
      <template #suffix>
        <BsIconStar />
      </template>
      Hello
    </BsButton>

    <BsButton :square="true" aria-label="Add to cart">
      <BsIconAdd />
    </BsButton>
  </div>
</template>

<script lang="ts" setup>
import { BsButton, BsIconHome, BsIconStar, BsIconAdd } from '@barnstormer/vue';
</script>
