// apps/preview/nuxt/pages/showcases/Badge/BadgeBasic.vue
<template>
  <div class="flex gap-3">
    <BsButton class="relative" square variant="tertiary">
      <BsIconShoppingCart />
      <BsBadge :content="content" />
    </BsButton>

    <BsButton class="relative" square variant="tertiary">
      <BsIconShoppingCart />
      <BsBadge :content="maxContent" />
    </BsButton>

    <BsButton class="relative" square variant="tertiary">
      <BsIconShoppingCart />
      <BsBadge :content="textContent" />
    </BsButton>

    <BsButton class="relative" square variant="tertiary">
      <BsIconShoppingCart />
      <BsBadge variant="dot" />
    </BsButton>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { BsBadge, BsButton, BsIconShoppingCart } from '@barnstormer/vue';

const content = ref(10);
const maxContent = ref(10000);
const textContent = ref('New');
</script>

// apps/preview/next/pages/showcases/Badge/BadgeBasic.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsBadge, BsButton, BsIconShoppingCart } from '@barnstormer/react';

export default function BadgeBasic() {
  return (
    <div className="flex gap-3">
      <BsButton className="relative" square variant="tertiary">
        <BsIconShoppingCart />
        <BsBadge content={10} />
      </BsButton>

      <BsButton className="relative" square variant="tertiary">
        <BsIconShoppingCart />
        <BsBadge content={10000} />
      </BsButton>

      <BsButton className="relative" square variant="tertiary">
        <BsIconShoppingCart />
        <BsBadge content="New" />
      </BsButton>

      <BsButton className="relative" square variant="tertiary">
        <BsIconShoppingCart />
        <BsBadge variant="dot" />
      </BsButton>
    </div>
  );
}

// #endregion source
BadgeBasic.getLayout = ShowcasePageLayout;
