// apps/preview/nuxt/pages/showcases/QuantitySelector/Rounded.vue
<template>
  <div class="flex">
    <BsButton
      square
      class="!rounded-full"
      :disabled="count <= min"
      :aria-controls="inputId"
      aria-label="Decrease value"
      @click="dec()"
    >
      <BsIconRemove />
    </BsButton>
    <input
      :id="inputId"
      v-model="count"
      type="number"
      class="appearance-none px-2 mx-2 w-12 text-center bg-transparent font-medium [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-inner-spin-button]:display-none [&::-webkit-inner-spin-button]:m-0 [&::-webkit-outer-spin-button]:display-none [&::-webkit-outer-spin-button]:m-0 [-moz-appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none disabled:placeholder-disabled-900 focus-visible:outline focus-visible:outline-offset focus-visible:rounded-sm"
      :min="min"
      :max="max"
      @input="handleOnChange"
    />

    <BsButton
      square
      class="!rounded-full"
      :disabled="count >= max"
      :aria-controls="inputId"
      aria-label="Increase value"
      @click="inc()"
    >
      <BsIconAdd />
    </BsButton>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { useCounter } from '@vueuse/core';
import { BsButton, BsIconAdd, BsIconRemove, useId } from '@barnstormer/vue';
import { clamp } from '@barnstormer/shared';

const min = ref(1);
const max = ref(10);
const inputId = useId();
const { count, inc, dec, set } = useCounter(1, { min: min.value, max: max.value });

function handleOnChange(event: Event) {
  const currentValue = (event.target as HTMLInputElement)?.value;
  const nextValue = parseFloat(currentValue);
  set(Number(clamp(nextValue, min.value, max.value)));
}
</script>

// apps/preview/next/pages/showcases/QuantitySelector/Rounded.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { BsButton, BsIconAdd, BsIconRemove } from '@barnstormer/react';
import { useCounter } from 'react-use';
import { useId, ChangeEvent } from 'react';
import { clamp } from '@barnstormer/shared';

export default function QuantitySelector() {
  const inputId = useId();
  const min = 1;
  const max = 10;
  const [value, { inc, dec, set }] = useCounter(min);
  function handleOnChange(event: ChangeEvent<HTMLInputElement>) {
    const { value: currentValue } = event.target;
    const nextValue = parseFloat(currentValue);
    set(Number(clamp(nextValue, min, max)));
  }
  return (
    <div className="inline-flex flex-col items-center">
      <div className="flex">
        <BsButton
          square
          className="!rounded-full"
          disabled={value <= min}
          aria-controls={inputId}
          aria-label="Decrease value"
          onClick={() => dec()}
        >
          <BsIconRemove />
        </BsButton>
        <input
          id={inputId}
          type="number"
          role="spinbutton"
          className="appearance-none px-2 mx-2 w-12 text-center bg-transparent font-medium [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-inner-spin-button]:display-none [&::-webkit-inner-spin-button]:m-0 [&::-webkit-outer-spin-button]:display-none [&::-webkit-outer-spin-button]:m-0 [-moz-appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none disabled:placeholder-disabled-900 focus-visible:outline focus-visible:outline-offset focus-visible:rounded-sm"
          min={min}
          max={max}
          value={value}
          onChange={handleOnChange}
        />

        <BsButton
          square
          className="!rounded-full"
          disabled={value >= max}
          aria-controls={inputId}
          aria-label="Increase value"
          onClick={() => inc()}
        >
          <BsIconAdd />
        </BsButton>
      </div>
    </div>
  );
}

// #endregion source
QuantitySelector.getLayout = ShowcasePageLayout;
